! DEFINE LAS ESTRUCTURAS DE DATOS DEL PROGRAMA OMCM

MODULE ESTRUCT

	INTEGER*4,PARAMETER :: ILONG=150		!LONGITUD MAXIMA DE LAS FUNCIONES DE BASE (CADENA DE CARACTERES)
	INTEGER*4,PARAMETER :: DLONG=300
	INTEGER*4,PARAMETER :: MAXGRAD=50		!GRADO MÁXIMO DE UN POLINOMIO

     TYPE RECORTADAS
        REAL*16 R0				!RADIO DE CORTE INICIAL PARA LA FUNCION DE BASE
		REAL*16 R1				!RADIO DE CORTE FINAL PARA LA FUNCION DE BASE
		REAL*16 D0				!DISTANCIA DE TRANSICION EN EL CORTE PARA R0
		REAL*16 D1				!DISTANCIA DE TRANSICION EN EL CORTE PARA R1
		INTEGER*4 TIPORECORT	!NOS DICE EL INTERVALO DE RECORTE 0=(0,R) 1=(R,INF) 2=(R0,R1)
		REAL*16 COEF(6)			!COEFICIENTES DEL AJUSTE DE LA FUNCION RECORTADA
    END TYPE
    
    TYPE SF_BASE
		CHARACTER*ILONG NOMBRE	!EXPRESION MATEMATICA DE LA FUNCION DE BASE
		INTEGER*4 N_SFBASE		!NUMERO DE LA SUBFUNCION DE BASE (CADA UNA DEL DESARROLLO)
        REAL*16 SCNOR            !CONSTANTE DE NORMALIZACIÓN DE LA SUBFUNCIÓN (QUE HABRÁ QUE MULTIPLICARLA POR EL COEFICIENTE QUE LE DEMOS A LA SUBFUNCIÓN EN LOS DATOS)
        REAL*16 COEFICIENTE      !COEFICIENTE PARA LOS DESARROLLOS QUE SE DA EN LOS DATOS
        REAL*16 PARAMETRO1       !PARA FUNCIONES EXPONENCIALES COEFICIENTE*R^P1*EXP(-P2*R-P3*R^2) O BIEN PARA BOX COEFICIENTE*R^P1*(R-P2)^P3
        REAL*16 PARAMETRO2
        REAL*16 PARAMETRO3
    END TYPE
	
    TYPE F_BASE
		CHARACTER*ILONG NOMBRE	                !EXPRESION MATEMATICA DE LA FUNCION DE BASE
		INTEGER*4 N_FBASE		                !NUMERO DE LA FUNCION DE BASE
		INTEGER*4 NTF			                !PARTES ANGULARES DE LA FUNCION DE BASE
		REAL*16 ANOR				                !CONSTANTE DE NORMALIZACION DE LA FUNCION DE BASE
		INTEGER*4 NC			                !NUMERO DE CENTRO DE LA F. DE BASE
		REAL*16 X				                !POSICION X DE LA F. DE BASE
		REAL*16 Y				                !POSICION Y DE LA F. DE BASE
		REAL*16 Z				                !POSICION Z DE LA F. DE BASE
		INTEGER*4 NSFB                          !Nº DE SUBFUNCIONES QUE FORMAN CADA FUNCION DE BASE
        TYPE (RECORTADAS) :: RECOR              !DATOS DEL RECORTE
        TYPE (SF_BASE),ALLOCATABLE :: SFB(:)    !ESTRUCTURA DE LAS SUBFUNCIONES DE BASE
    END TYPE

    TYPE FGAUSS     			!GAUSSIANA=GNOR*X^L*Y^M*Z^N*EXP(-GEXP*R^2)
		REAL*16 GNOR				!CTE DE NORMALIZACION DE LA GAUSS.
		REAL*16 GEXP				!EXPONENTE DE LA GAUSSIANA
		REAL*16 GCOEF			!COEFICIENTE DE LA GAUSIANA DEBIDO AL DESARROLLO NG
		INTEGER*4 GNX				!NX: POTENCIA DE LA X
		INTEGER*4 GNY				!NY: POTENCIA DE LA Y
		INTEGER*4 GNZ				!NZ: POTENCIA DE LA Z
    END TYPE
    
	TYPE NUCLEO
		INTEGER*4 N_NUC			!NUMERO DEL NUCLEO
		REAL*16 X				!POSICION X DEL NUCLEO
		REAL*16 Y				!POSICION Y DEL NUCLEO
		REAL*16 Z				!POSICION Z DEL NUCLEO
		REAL*16 CARGA			!CARGA NUCLEAR
		INTEGER*4 NC			!CENTRO DEL NUCLEO
		CHARACTER*ILONG NOMBRE	!NOMBRE DEL NÚCLEO
	END TYPE

	TYPE CENTRO
		INTEGER*4 NC			!NUMERO DEL CENTRO
		REAL*16 X				!POSICION X 
		REAL*16 Y				!POSICION Y 
		REAL*16 Z				!POSICION Z 
	END TYPE

	TYPE DAT_ITERAT
		CHARACTER*3 THF
						!THF (='RHF' O 'UHF') ES EL TIPO DE CALCULO SCF.
							!RHF -> HARTREE-FOCK RESTRINGIDO
							!UHF -> HARTREE-FOCK NO RESTRINGIDO.
		INTEGER*4 ITMET
						!ITMET (=0,1,2 ) DA LA FORMA DE ITERAR:
							!0 -> POR PANTALLA
							!1 -> CONVERGENCIA EN ENERGIA
							!2 -> CONVERGENCIA EN COEFICIENTES
		INTEGER*4 MAXITER	
						!Nº DE ITERACIONES MÁXIMAS
		REAL*16 CONV
						!CONV ES EL CRITERIO DE CONVERGENCIA. SUS VALORES TIPICOS
							!PODRIAN SER, POR EJEMPLO:
							!CONV -> 1.E-6 SI ITMET=1
							!CONV -> 1.E-3 SI ITMET=2
		REAL*16 F_CONV	!FACTOR DE AMORTIGUACIÓN EN LAS ITERACIONES
							!0 -> NO SE AMORTIGUA
							!0<F_CONV<1 -> SE AMORTIGUA
							!1 -> NO ITERA
		INTEGER*4 NIT_CONV !ITERACION INICIAL PARA AMORTIGUAR
	END TYPE

	TYPE DAT_METODO	!DETERMINADOS VALORES QUE NECESITAN LOS DISTINTOS METODOS DE GENERACION DE NUMEROS ALEATORIOS
		INTEGER*4 NUM			!VALIDO PARA HAL,HAM
		INTEGER*4 NR1			!VALIDO PARA HAL,HAM
		INTEGER*4 NR2			!VALIDO PARA HAL,HAM
		REAL*16 RAIZ			!VALIDO PARA HAS
		REAL*16 DNUMERO		!VALIDO PARA HAS
	END TYPE

	TYPE FICHEROS
		CHARACTER*ILONG DAT	!NOMBRE DEL FICHERO DE DATOS
		CHARACTER*ILONG INT	!NOMBRE DEL FICHERO DE INTEGRALES
		CHARACTER*ILONG RES	!NOMBRE DEL FICHERO DE RESULTADOS TOTALES
		CHARACTER*ILONG MIN	!NOMBRE DEL FICHERO DE RESULTADOS MINIMOS
		CHARACTER*ILONG SCR	!NOMBRE DEL FICHERO SCRATCH
		CHARACTER*ILONG MTD	!NOMBRE DEL FICHERO DEL METODO DE CALCULO
		CHARACTER*ILONG PRP	!NOMBRE DEL FICHERO DE PROPIEDADES MOLECULARES
		CHARACTER*ILONG AUX !ALMACENA LAS INTEGRALES EN UN ARCHIVO AUXILIAR (PARA RAPIDEZ EN LECTURA)
		CHARACTER*ILONG GSA !NOMBRE DEL FICHERO DE DESARROLLOS GAUSSIANOS
	END TYPE

	TYPE DIRECTORIOS
		CHARACTER*DLONG DAT	!DIRECTORIO DE ARCHIVOS DATOS
		CHARACTER*DLONG RES	!DIRECTORIO DE ARCHIVOS RESULTADOS TOTALES
		CHARACTER*DLONG MIN	!DIRECTORIO DE ARCHIVOS RESULTADOS MINIMOS
		CHARACTER*DLONG INT	!DIRECTORIO DE ARCHIVOS INTEGRALES
		CHARACTER*DLONG SCR	!DIRECTORIO DE ARCHIVOS SCRATCH
		CHARACTER*DLONG MTD	!DIRECTORIO DE ARCHIVOS DEL METODO DE CÁLCULO
		CHARACTER*DLONG PRP	!DIRECTORIO DE ARCHIVOS DE PROPIEDADES MOLECULARES
		CHARACTER*DLONG AUX !DIRECTORIO DE ARCHIVOS AUXILIARES DE INTEGRALES
		CHARACTER*DLONG GSA !DIRECTORIO DE ARCHIVOS DE DESARROLLOS GAUSSIANOS
	END TYPE

	TYPE CF     		  ! ESTRUCTURA PARA CODIFICAR LAS FUNCIONES DE BASE
		INTEGER*1 NUM     ! NUMERO DE LA FUNCION DE BASE
		CHARACTER*ILONG F ! FORMULA MATEMATICA DE LA FUNCION
		INTEGER*1 ORD     ! ORDEN EN EL QUE SE REALIZA LA OPERACION
		INTEGER*1 NVI     ! NUMERO DE MONOMIOS*3 N*R^M (UNO PARA CADA VALOR)
		REAL*16 VI(90)     ! VALOR DE LOS NVI
		INTEGER*1 NM      ! NUMERO DE MONOMIOS EN TOTAL
		INTEGER*4 M(30)   ! CODIGOS DE LOS MONOMIOS
		INTEGER*1 NP      ! NUMERO DE POLINOMIOS
		INTEGER*4 P(30)   ! CODIGOS DE LOS POLINOMIOS
		INTEGER*1 NF      ! NUMERO DE FUNCIONES
		INTEGER*4 FU(30)  ! CODIGOS DE LAS FUNCIONES
    END TYPE

	TYPE XYZ
		REAL*16 X
		REAL*16 Y
		REAL*16 Z
	END TYPE
	TYPE RCSTFI
		REAL*16 R
		REAL*16 CST
		REAL*16 FI
	END TYPE
	TYPE XY
		REAL*16 X
		REAL*16 Y
	END TYPE
	TYPE NNN
		INTEGER*4 NX
		INTEGER*4 NY
		INTEGER*4 NZ
	END TYPE

	TYPE POLINOMIO
		INTEGER*4 GRADO
		REAL*16 C(0:MAXGRAD)
	END TYPE

	TYPE (F_BASE), ALLOCATABLE :: FB(:)
    TYPE (FGAUSS), ALLOCATABLE::GAUSS(:,:)
    TYPE (FGAUSS), ALLOCATABLE::GAUSS2(:,:)
    TYPE (NUCLEO), ALLOCATABLE :: NUCLEOS(:)
    TYPE (CENTRO),ALLOCATABLE :: CENTROS(:)
    TYPE (CF),ALLOCATABLE :: CFUNC(:)
	
    TYPE (DAT_ITERAT) :: DI
	TYPE (FICHEROS) :: FICH
	TYPE (DIRECTORIOS) :: DIR
	CHARACTER*DLONG DIRE

	TYPE (NNN) :: NN	!VALORES NECESARIOS EN LAS INTEGRALES DE MOMENTO
	TYPE (XYZ) :: P0	!				"

END MODULE ESTRUCT

MODULE GLOBAL

	CHARACTER*60 COMENT
	INTEGER*4 ICASO	!CASO QUE TRATAMOS (TODO EL PROGRAMA SE REPITE PARA TODOS LOS CASOS DE DATOS QUE QUERAMOS)
	CHARACTER*7 CLASRES

	REAL*16,PARAMETER :: CERO=1.Q-24
	REAL*16,PARAMETER :: VALINF=1.Q15 
	REAL*16,PARAMETER :: PI=3.141592653589793238Q0
	!REAL*16 CERO
	!REAL*16 VALINF
	!REAL*16 PI

	INTEGER*4 NUC		!NUMERO DE NUCLEOS
	INTEGER*4 NCENTROS	!NUMERO DE CENTROS
    INTEGER*4 NINTBI    !NUMERO DE INTEGRALES BIELECTRÓNICAS
    
	INTEGER*4 N			!NUMERO DE FUNCIONES DE BASE
	INTEGER*4 RECORT	!NOS DICE SI NO UTILIZAMOS FUNCIONES RECORTADAS =0, CAJA RÍGIDA =1, CAJA BLANDA =2
    INTEGER*4 BIELEC    !NOS DICE SI QUEREMOS DISCRIMINAR EL CÁLCULO DE LAS INTEGRALES BIELECTRÓNICAS EN FUNCIÓN DE LA DISTANCIA DE LOS CENTROS Y EL RADIO DE RECORTE
	REAL*16 R0,R1,EXP0	!RADIO DE CORTE Y EXPONENTE DE LA FUNCIÓN DE PESO
	REAL*16 MU0,MU1,EXP1	!MU DE CORTE Y EXPONENTE DE LA FDP EN PARA LA COORDENADA MU EN ELIPSOIDALES
	INTEGER*4 TIPOFB	!TIPOS DE FUNCIONES DE BASE: 0=DEFINIDAS POR USUARIO, 1=STOxGTO O DESARROLLOS DE STOxGTO (INTEGRACION NUMERICA), 2=BOX O DESARROLLOS DE BOX, 3 = DESARROLLOS EN GTO (INTEGRACIÓN ANALÍTICA)
    INTEGER*4 NORMSFB   !=1 SI SE SUPONEN LAS SUBFUNCIONES YA NORMALIZADAS (PORQUE LOS COEFICIENTES SE LE HAN DADO SUPONIENDO QUE ESTÁN NORMALIZADAS, ESTO SE SUELE HACER EN LOS BOX) O =0 NO NORMALIZAR LAS SUBFUNCIONES (ESTO ES TIPICO EN H-OIDES)
    
	CHARACTER*3 CLASMON		
							!CLASMON INDICA EL TIPO DE INTEGRACION:
							!CLASMON -> 'HAS' : INTEGRALES POR HASELGROVE
							!CLASMON -> 'HAM' : INTEGRALES POR HAMMERSLEY
							!CLASMON -> 'HAL' : INTEGRALES POR HALTON
							!CLASMON -> 'RND' : INTEGRALES POR MC ORDINARIO
							!CLASMON -> 'LEE' : INTEGRALES DEL FICHERO 'DATINT'.
	INTEGER*4 NMC	!NUMERO DE PUNTOS PARA LA INTEGRACION
	INTEGER*4 ISEM	!SEMILLA (SOLO PARA EL METODO QUE LA NECESITA)
	CHARACTER*1 CLASINT	!NOS DICE EL TIPO DE INTEGRAL QUE CALCULA: S,H,X,J
	CHARACTER*1 CLASNOR
	INTEGER*4 UNASOLA    !NOS DICE SI CALCULAMOS UNA SOLA INTEGRAL(1) O TODAS(0)
	CHARACTER*1 STIPO    !NOS DICE EL TIPO DE INTEGRAL QUE CALCULA (CUANDO SÓLO ES UNA): S,H,X,J
	INTEGER*4 SN1,SN2,SN3,SN4 !CODIGOS DE LA INTEGRAL A CALCULAR
	REAL*16 INTEGRAL		!INTEGRAL CALCULADA CUANDO ES UNA SOLA
	REAL*16 ERINTS		!ERROR COMETIDO EN LA INTEGRAL

	INTEGER*4 N_INT		!ELEMENTOS DE LAS MATRICES DE INTEGRALES SIMETRICAS SIN LA DIAGONAL PRINCIPAL
	INTEGER*4 N_INT_D		!ELEMENTOS DE LAS MATRICES DE INTEGRALES SIMETRICAS CON LA DIAGONAL PRINCIPAL
	INTEGER*4 N_INT_BI	!NUMERO DE INTEGRALES BIELECTRONICAS DIFERENTES

	REAL*16,ALLOCATABLE ::S(:)	!ELEMENTOS (INTEGRALES) DE LA MATRIZ S
	REAL*16 ESMED				!ERROR MEDIO PARA LOS ELEMENTOS DE LA MATRIZ S
	REAL*16 ESMAX				!ERROR MAXIMO PARA LOS ELEMENTOS DE LA MATRIZ S
	
	REAL*16,ALLOCATABLE ::H(:)	!ELEMENTOS (INTEGRALES) DE LA MATRIZ H
	REAL*16 EHMED				!ERROR MEDIO PARA LOS ELEMENTOS DE LA MATRIZ H
	REAL*16 EHMAX				!ERROR MAXIMO PARA LOS ELEMENTOS DE LA MATRIZ H
	
	REAL*16,ALLOCATABLE ::T(:)	!ELEMENTOS (INTEGRALES) DE LA MATRIZ DE ENERGÍA CINÉTICA
	REAL*16 ETMED				!ERROR MEDIO PARA LOS ELEMENTOS DE LA MATRIZ T
	REAL*16 ETMAX				!ERROR MAXIMO PARA LOS ELEMENTOS DE LA MATRIZ T
	
	REAL*16,ALLOCATABLE ::V(:)	!ELEMENTOS (INTEGRALES) DE LA MATRIZ DE ENERGÍA POTENCIAL
	REAL*16 EVMED				!ERROR MEDIO PARA LOS ELEMENTOS DE LA MATRIZ V
	REAL*16 EVMAX				!ERROR MAXIMO PARA LOS ELEMENTOS DE LA MATRIZ V


	REAL*16,ALLOCATABLE ::R(:)	!MATRIZ DE INTEGRALES BIELECTRONICAS
	REAL*16 ERMED				!ERROR MEDIO PARA LOS ELEMENTOS DE LA MATRIZ DE INTEGRALES BIELECTRONICAS
	REAL*16 ERMAX				!ERROR MAXIMO PARA LOS ELEMENTOS DE LA MATRIZ DE INTEGRALES BIELECTRONICAS
	INTEGER*1, ALLOCATABLE :: NK(:)	!MATRIZ QUE NOS DICE SI LA INTEGRAL BIELECTRONICA YA HA SIDO ALMACENADA

	REAL*16,ALLOCATABLE ::XMAT(:)	!MATRIZ DE INTEGRALES DE MOMENTO EN EL EJE X
	REAL*16 EXMED
	REAL*16 EXMAX
	REAL*16,ALLOCATABLE ::YMAT(:)	!MATRIZ DE INTEGRALES DE MOMENTO EN EL EJE Y
	REAL*16 EYMED
	REAL*16 EYMAX
	REAL*16,ALLOCATABLE ::ZMAT(:)	!MATRIZ DE INTEGRALES DE MOMENTO EN EL EJE Z
	REAL*16 EZMED
	REAL*16 EZMAX

	REAL*16,ALLOCATABLE :: VGSS(:,:,:,:)  !MATRIZ PARA LAS BIELECTRÓNICAS CON FUNCIONES DE BASE GAUSSIANAS
	
	REAL*16,ALLOCATABLE :: EORA(:),EORB(:)  !MATRIZ DE LAS ENERGÍAS ORBITALES ALFA Y BETA

	INTEGER*4 NPOLIG  !NUMERO DE POLIGONALES A EMPLEAR: 1, 2 Ó 3
	REAL*16 INIR			!INICIO DEL INTERVALO PARA LA FUNCION DE PESO
    REAL*16 FINR			!FIN DEL INTERVALO PARA LA FUNCION DE PESO
    INTEGER*4 INCREMENT	!DIVISIONES DEL INTERVALO PARA LA FUNCION DE PESO
    REAL*16 A0,CEXP		!EXPONENTE Y CONSTANTE DE NORMALIZACION DE LA EXPONENCIAL EN LA FUNCION DE PESO
	REAL*16 INIA
    REAL*16 FINA
    

	CHARACTER*3 SCF	!MÉTODO SCF: HF=HARTREE FOCK, MP2= MOLER PLESET 2

	INTEGER*4,ALLOCATABLE :: NOC(:)
	INTEGER*4,ALLOCATABLE :: NOCA(:)	!NUMERO DE OCUPACION PARA EL ORBITAL (ALFA O BETA) 
	INTEGER*4,ALLOCATABLE :: NOCB(:)
	REAL*16,ALLOCATABLE :: CA(:,:)
	REAL*16,ALLOCATABLE :: CB(:,:)
	REAL*16,ALLOCATABLE :: C0A(:,:)
	REAL*16,ALLOCATABLE :: C0B(:,:)
	REAL*16,ALLOCATABLE :: PA(:,:)
	REAL*16,ALLOCATABLE :: PB(:,:)

	REAL*16,ALLOCATABLE :: ENEL(:)	!ENERGIA ELECTRONICA
	REAL*16,ALLOCATABLE :: VIRIAL(:) !VIRIAL
	REAL*16 TMEDIA,VMEDIA			!ENERGÍA CINETICA MEDIA, ENERGÍA POTENCIAL MEDIA
	REAL*16 EREP						!ENERGIA DE REPULSION NUCLEAR
	REAL*16 ENELTOT,ETOT				!ENERGIA ELECTRONICA FINAL, ENERGÍA TOTAL
	REAL*16 ECMP2					!CORRECCIÓN DE LA ENERGIA MP2
		
	REAL*16 POT(3)		!VALORES DEL POTENCIAL EXTERNO: POTX,POTY,POTZ
	
	INTEGER*4 NEL		!VALOR PARA LOS NUMEROS DE OCUPACION ALFA Y BETA (NUMERO DE ELECTRONES)
	
	INTEGER*4 MOMENTODIPOLAR,POBLACIONES	!VARIABLES PARA EL CÁLCULO DE PROPIEDADES
	REAL*16 PXEL,PYEL,PZEL,PXNUC,PYNUC,PZNUC,PTX,PTY,PTZ,PMODUL	!MOMENTO DIPOLAR
	REAL*16,ALLOCATABLE :: POBEL(:),POSX(:),POSY(:),POSZ(:),DPX(:),DPY(:),DPZ(:) !POBLACIONES

	INTEGER*4 ESCRITURA(0:13)	!VARIABLES PARA LA ESCRITURA DE RESULTADOS

	CHARACTER*20 IDIOMA

END MODULE GLOBAL

