! -------------------------------------------------------------------
! --- SUBPROGRAMA PARA ESCRIBIR DATOS Y RESULTADOS DE FORMA ELEGANTE
! -------------------------------------------------------------------
	SUBROUTINE ESCRIBIR(FICHERO,NUMINTBI)
	USE GLOBAL
	USE ESTRUCT
	CHARACTER*(*) FICHERO
	CHARACTER*ILONG LEERVALOR,INTTOSTR
    INTEGER*4 NUMINTBI
	REAL*16 LEERVALOR_REAL
	
	IDIOMA=LEERVALOR('idioma.lng','idioma','idioma')
		
	CALL DEFINE_FICH(FICH.DAT,DIR.DAT,TRIM(FICHERO),'DAT')
	CALL DEFINE_FICH(FICH.MTD,DIR.MTD,TRIM(FICHERO),'MTD')
	CALL DEFINE_FICH(FICH.PRP,DIR.PRP,TRIM(FICHERO),'PRP')
	CALL DEFINE_FICH(FICH.RES,DIR.RES,TRIM(FICHERO),'RES')
	CALL LEEDAT() !LECTURA DEL FICHEO DE DATOS
	CALL DEFINE_FICH(FICH.INT,DIR.INT,FICH.INT,'INT')
    CALL DEFINE_FICH(FICH.AUX,DIR.AUX,TRIM(FICHERO),'AUX')
	CALL DEFINE_FICH(FICH.GSA,DIR.GSA,'BASES','DAT')
    
    IF(TIPOFB>0)THEN !SOLO PARA LAS QUE SON DESARRORROS (NO LAS GENERICAS)
        DO I=1,N
            DO J=1,FB(I).NSFB
				FB(I).SFB(J).SCNOR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',normalizacion)')
            ENDDO
        ENDDO
    ENDIF
    
	OPEN(UNIT=5,FILE=DIR.RES,STATUS='UNKNOWN')
	
    NINTBI=NUMINTBI
    
	IF (UNASOLA==0)THEN
		CALL LEETOQASINT()
		CALL ESCR
	ELSE
		CALL ESCR_SOLOUNA
	ENDIF
	
	CLOSE(5)
	
    END SUBROUTINE
        
! -------------------------------------------------------------------
! --- SUBPROGRAMA PARA ESCRIBIR DATOS Y RESULTADOS
! -------------------------------------------------------------------
	SUBROUTINE ESCR
    USE GLOBAL
	USE ESTRUCT
	CHARACTER*ILONG CADENA,CADENA1
	CHARACTER*ILONG INTTOSTR,LEERVALOR
	INTEGER*4 LEERVALOR_INT,NVAR,ERROR
	REAL*16 LEERVALOR_REAL,VAR1,VAR2,GCOEF,GEXP
	CHARACTER*12 SPD(0:15)
	INTEGER*4 I,II,J,IP,IQ,IR,IS,ICONT,NG,M


	DATA SPD /'S','Px','Py','Pz','D(x²-y²)','Dxy','Dxz','Dyz','D(3z²-r²)', &
	 'F(x³-3y²x)','F(y³-3x²y)','F(x²-y²)z','Fxyz','F(xr²-5xz²)','F(yr²-5yz²)','F(5z³-3r²z)'/

	IF (ESCRITURA(0)==1)THEN	!CABEZERA
		CALL SEPARADOR(78,3,0,5)
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1250')
		WRITE(5,'(8X,A)')TRIM(CADENA)
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'116')
		WRITE(5,'(/,8X,A)')'D. ZORRILLA & M. FERNANDEZ'
		CALL SEPARADOR(78,3,0,5)
	ENDIF

	IF (ESCRITURA(1)==1)THEN	!DATOS
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1251')
		WRITE(5,'(/,4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(NUC))
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1252')
		WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(N))
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1253')
		WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(CLASMON)
		IF(CLASMON=='HAS'.OR.CLASMON=='HAL'.OR.CLASMON=='HAM'.OR.CLASMON=='RND')THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1254')
			WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(NMC))
            !CADENA=LEERVALOR('idioma.lng',IDIOMA,'1245')
            !WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(ISEM))
		ELSEIF(CLASMON=='GSS')THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1244')
            !NGAUSS=LEERVALOR_INT(DIR.INT,'FBASE','NumGauss')
			NGAUSS=0
            DO I=1,N
                NGAUSS=NGAUSS+FB(I).NSFB
            ENDDO
			WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(NGAUSS))
		ENDIF
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1255')
		WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(SCF)
        CADENA=LEERVALOR('idioma.lng',IDIOMA,'1321')
		IF(NUMSFB==0)THEN
            CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1322')
        ELSE
            CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1323')
        ENDIF
        WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(CADENA1)
        
		CALL SEPARADOR(78,1,1,5)

		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1256')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1243')
		CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1257')
		WRITE(5,'(/,T7,A,T22,A,T37,A1,T48,A1,T59,A1)')TRIM(CADENA),TRIM(CADENA1),'X','Y','Z'
		WRITE(5,'(4X,A,6X,A,6X,A)')'----------','-------','-----------------------------'
		DO I=1,NUC
            WRITE(5,'(4X,A,7X,F6.2,4X,F10.5,1X,F10.5,1X,F10.5)')TRIM(NUCLEOS(I).NOMBRE),NUCLEOS(I).CARGA,NUCLEOS(I).X,NUCLEOS(I).Y,NUCLEOS(I).Z
		ENDDO

		CALL SEPARADOR(78,1,1,5)

		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1258')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1259')
		CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1260')
		
        IF(TIPOFB==0)THEN
            WRITE(5,'(/,T6,A,T26,A,T65,A)')'N',TRIM(CADENA),TRIM(CADENA1)
		    WRITE(5,'(4X,A,1X,A,3X,A)')'---','----------------------------------------------------','---------------'
			DO I=1,N
				WRITE(5,'(4X,I3,1X,A,T67,A)')I,FB(I).NOMBRE,SPD(FB(I).NTF)
			ENDDO
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1261')
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1262')
			WRITE(5,'(/,4X,A,A1,I3,A,A1,I5)')TRIM(CADENA),':',NPOLIG,TRIM(CADENA1),':',INCREMENT+1
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1263')
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1264')
			WRITE(5,'(4X,A,A1,F10.5,A,A1,F10.5)')TRIM(CADENA),':',INIR,TRIM(CADENA1),':',FINR
        ELSEIF(TIPOFB==1)THEN
			WRITE(5,'(/,T6,A,3X,A,T26,A,T65,A)')'N','S',TRIM(CADENA),TRIM(CADENA1)
		    WRITE(5,'(4X,A,1X,A,1X,A,3X,A)')'---','---','--------------------------------------------------','---------------'
		    DO I=1,N
				DO J=1,FB(I).NSFB
                    IF(FB(I).SFB(J).PARAMETRO1==0.Q0)THEN
                        WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F8.5,A,F6.3,A,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR,' EXP(-',FB(I).SFB(J).PARAMETRO2,' r -',FB(I).SFB(J).PARAMETRO3,' R^2)',SPD(FB(I).NTF)
                    ELSE
                        WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F6.3,A,F8.5,A,F6.3,A,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR,' r^',FB(I).SFB(J).PARAMETRO1,' EXP(-',FB(I).SFB(J).PARAMETRO2,' r -',FB(I).SFB(J).PARAMETRO3,' R^2)',SPD(FB(I).NTF)
                    ENDIF
                ENDDO
            ENDDO
        ELSEIF(TIPOFB==2)THEN
            WRITE(5,'(/,T6,A,3X,A,T26,A,T65,A)')'N','S',TRIM(CADENA),TRIM(CADENA1)
		    WRITE(5,'(4X,A,1X,A,1X,A,3X,A)')'---','---','--------------------------------------------------','---------------'
			DO I=1,N
                DO J=1,FB(I).NSFB
                    IF(FB(I).SFB(J).PARAMETRO1==0.Q0)THEN
                        WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F8.5,A,F6.3,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR*2.Q0*QSQRT(PI)*FB(I).ANOR,' (',FB(I).SFB(J).PARAMETRO2,' - r)^',FB(I).SFB(J).PARAMETRO3,SPD(FB(I).NTF)
                    ELSE
					    WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F6.3,A,F8.5,A,F6.3,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR*2.Q0*QSQRT(PI)*FB(I).ANOR,'r^',FB(I).SFB(J).PARAMETRO1,' (',FB(I).SFB(J).PARAMETRO2,' - r)^',FB(I).SFB(J).PARAMETRO3,SPD(FB(I).NTF)
                    ENDIF
                ENDDO
            ENDDO
		ENDIF
		
		
	
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1265')
		WRITE(5,'(/,4X,A,A1)')TRIM(CADENA),':'
		WRITE(5,'(/,T6,A,T15,A,T26,A,T37,A)')'N','X','Y','Z'
		WRITE(5,'(4X,A,4X,A)')'---','-----------------------------'
		DO I=1,N
			WRITE(5,'(4X,I2,2X,F10.5,1X,F10.5,1X,F10.5)')I,FB(I).X,FB(I).Y,FB(I).Z
		ENDDO

		IF(RECORT==1.OR.RECORT==2) THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1266')
			WRITE(5,'(/,4X,A,A1)')TRIM(CADENA),':'
			WRITE(5,'(/,5X,A,8X,A,14X,A)')'N','R0','D'
			WRITE(5,'(4X,A,3X,A,4X,A)')'---','-----------','-----------'
			DO I=1,N
				WRITE(5,'(4X,I3,2X,F10.5,6X,F10.5)')I,FB(I).RECOR.R1,FB(I).RECOR.D1
			END DO
		ENDIF

		CALL SEPARADOR(78,1,1,5)
		
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1267')
		WRITE(5,'(4X,A,A1,/)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1268')
        WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
        M=N/10
        I=1
        DO J=1,M
            WRITE(5,'(16X,10I2)')(NOCA(II),II=I,I+9)
            I=J*10+1
		ENDDO
        CADENA=LEERVALOR('idioma.lng',IDIOMA,'1269')
        WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
        I=1
        DO J=1,M
            WRITE(5,'(16X,10I2)')(NOCB(II),II=I,I+9)
            I=J*10+1
		ENDDO

		IF(POT(1)/=CERO.OR.POT(2)/=CERO.OR.POT(3)/=CERO)THEN
			CALL SEPARADOR(78,1,1,5)
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1270')
			WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
			WRITE(5,'(/,T9,A,T20,A,T31,A)')'X','Y','Z'
			WRITE(5,'(4X,A)')'-------------------------------'
			WRITE(5,'(4X,F8.4,3X,F8.4,3X,F8.4)')POT(1),POT(2),POT(3)
		ENDIF
	
		CALL SEPARADOR(78,3,1,5)
	ENDIF

	IF(ESCRITURA(2)==1)THEN	!MATRIZ DE SOLAPAMIENTO
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1271')
		WRITE(5,'(4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(S,1),N,S,6,5)	
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',ESMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',ESMAX
        ENDIF
		CALL SEPARADOR(78,1,1,5)
	ENDIF
	
	IF(ESCRITURA(3)==1)THEN	!MATRIZ DE ENERGIA CINETICA
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1274')
		WRITE(5,'(4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(T,1),N,T,6,5)
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',ETMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',ETMAX
        ENDIF
		CALL SEPARADOR(78,1,1,5)
	ENDIF
	
	IF(ESCRITURA(4)==1)THEN	!MATRIZ DE ENERGIA POTENCIAL
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1275')
		WRITE(5,'(4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(V,1),N,V,6,5)
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',EVMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',EVMAX
        ENDIF
		CALL SEPARADOR(78,1,1,5)
	ENDIF

	IF(ESCRITURA(5)==1)THEN	!MATRIZ DE ENERGIA MONOELECTRONICA
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1276')
		WRITE(5,'(4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(H,1),N,H,6,5)
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',EHMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',EHMAX
        ENDIF
		CALL SEPARADOR(78,1,1,5)
	ENDIF

	IF(ESCRITURA(6)==1)THEN	!MATRIZ DE MOMENTOS
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1277')
		WRITE(5,'(4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(H,1),N,XMAT,6,5)
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',EXMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',EXMAX
        ENDIF
        
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1278')
		WRITE(5,'(/,4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(H,1),N,YMAT,6,5)
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',EYMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',EYMAX
        ENDIF
        
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1279')
		WRITE(5,'(/,4X,A,A1,A2,I3,A2,I3,A2)')TRIM(CADENA),':',' (',N,' x',N,'):'
		CALL MATOUTL(SIZE(H,1),N,ZMAT,6,5)
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',EZMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',EZMAX		
        ENDIF
		CALL SEPARADOR(78,1,1,5)
    ENDIF

    
    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1280')
    WRITE(5,'(4X,A,A2,I10,A2,/)')TRIM(CADENA),' (',NINTBI,')'
	IF(ESCRITURA(7)==1)THEN	!INTEGRALES BIELECTRÓNICAS
		ICONT=0
		DO K=1,N_INT_BI
			IF (R(K)/=0.Q0) THEN
				ICONT=ICONT+1
				IF(ICONT>2)THEN
					ICONT=0
					CALL IND_PQRS(K,IP,IQ,IR,IS)
					WRITE(5,'(4X,4I2,A,F10.7,1X)',ADVANCE='YES')IP,IQ,IR,IS,' =',R(K)
				ELSE
					CALL IND_PQRS(K,IP,IQ,IR,IS)
					WRITE(5,'(4X,4I2,A,F10.7,1X)',ADVANCE='NO')IP,IQ,IR,IS,' =',R(K)
				ENDIF
			ENDIF
		ENDDO
        IF(CLASMON.NE."GSS") THEN
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1272')
		    WRITE(5,'(/,4X,A,A1,F9.5)')TRIM(CADENA),':',ERMED
		    CADENA=LEERVALOR('idioma.lng',IDIOMA,'1273')
		    WRITE(5,'(4X,A,A1,F9.5)')TRIM(CADENA),':',ERMAX 
		ENDIF
        CALL SEPARADOR(78,1,1,5)
	ENDIF
	
	CADENA='TIEMPO EMPLEADO EN LA INTEGRACIÓN'
	CADENA1=LEERVALOR(DIR.INT,'TIEMPO','TiempoIntegracion')
	WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(CADENA1)
	CALL SEPARADOR(78,3,1,5)

	IF(ESCRITURA(8)==1)THEN	!PROCESO SCF
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1281')
		WRITE(5,'(4X,A,A1,/)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1282')
		CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1283')
		NVAR=LEERVALOR_INT(DIR.MTD,'METODOCALCULO','NumMaxIter')
		VAR1=LEERVALOR_REAL(DIR.MTD,'METODOCALCULO','Tolerancia')
		WRITE(5,'(4X,A,A1,1X,I4,4X,A,A1,1X,G12.7,/)')TRIM(CADENA),':',NVAR,TRIM(CADENA1),':',VAR1
		
		VAR1=LEERVALOR_REAL(DIR.MTD,'METODOCALCULO','FactorAmortiguacion')
		IF (VAR1/=0.Q0)THEN
			NVAR=LEERVALOR_INT(DIR.MTD,'METODOCALCULO','FactorComienzoAmortiguacion')
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1284')
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1285')
			WRITE(5,'(4X,A,A1,1X,G12.7,4X,A,A1,1X,I4,/)')TRIM(CADENA),':',VAR1,TRIM(CADENA1),':',NVAR
		ENDIF

		NIT=LEERVALOR_INT(DIR.MTD,'ITERACIONES','NumIteraciones')
		DO I=0,NIT
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1221')
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1286')
			VAR1=LEERVALOR_REAL(DIR.MTD,'ITERACIONES','ENERGIA('//TRIM(INTTOSTR(I))//')')
			VAR2=LEERVALOR_REAL(DIR.MTD,'ITERACIONES','VIRIAL('//TRIM(INTTOSTR(I))//')')
			WRITE(5,'(4X,A5,I4,4X,A,A2,F22.15,3X,A,A2,G17.10)')'ITER.',I,TRIM(CADENA),' =',VAR1,TRIM(CADENA1),' =',VAR2
		ENDDO
		
		CALL SEPARADOR(78,1,1,5)
	ENDIF
	CADENA=LEERVALOR('idioma.lng',IDIOMA,'1287')
	CADENA1=LEERVALOR(DIR.MTD,'TIEMPO','TiempoSCF')
	WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(CADENA1)
	CALL SEPARADOR(78,3,1,5)

	IF(ESCRITURA(9)==1)THEN	!COEFICIENTES Y ENERGÍA ORBITAL
		DO I=1,N
			NOCA(I)=LEERVALOR_INT(DIR.MTD,'ESTADOELECTRONICO','NumOcupAlfa('//TRIM(INTTOSTR(I))//')')
			NOCB(I)=LEERVALOR_INT(DIR.MTD,'ESTADOELECTRONICO','NumOcupBeta('//TRIM(INTTOSTR(I))//')')
			EORA(I)=LEERVALOR_REAL(DIR.MTD,'ESTADOELECTRONICO','EnergiaOrbitalAlfa('//TRIM(INTTOSTR(I))//')')
			EORB(I)=LEERVALOR_REAL(DIR.MTD,'ESTADOELECTRONICO','EnergiaOrbitalBeta('//TRIM(INTTOSTR(I))//')')
		ENDDO
		DO I=1,N
			DO J=1,N
				CA(I,J)=LEERVALOR_REAL(DIR.MTD,'ESTADOELECTRONICO','CoefOcupAlfa('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')		
				CB(I,J)=LEERVALOR_REAL(DIR.MTD,'ESTADOELECTRONICO','CoefOcupBeta('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			ENDDO
		ENDDO
		
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1288')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		DO I=1,N
			IF(NOCA(I)==0)THEN
				CADENA=LEERVALOR('idioma.lng',IDIOMA,'1289')
			ELSE
				CADENA=LEERVALOR('idioma.lng',IDIOMA,'1290')
			ENDIF
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1221')
			IF (ABS(EORA(I))>500.Q0)THEN
				WRITE(5,'(/4X,A,I2,A1,1X,A,A2,F14.7,1X,A11,F11.4,A5)')TRIM(CADENA),I,':',TRIM(CADENA1),' =',EORA(I),'Hartrees ( ',EORA(I)*2.721161Q01,' eV )'
			ELSEIF (ABS(EORA(I))>2.Q0)THEN
				WRITE(5,'(/4X,A,I2,A1,1X,A,A2,F14.7,1X,A11,F10.4,A5)')TRIM(CADENA),I,':',TRIM(CADENA1),' =',EORA(I),'Hartrees ( ',EORA(I)*2.721161Q01,' eV )'
			ELSE
				WRITE(5,'(/4X,A,I2,A1,1X,A,A2,F14.7,1X,A11,F10.6,A5)')TRIM(CADENA),I,':',TRIM(CADENA1),' =',EORA(I),'Hartrees ( ',EORA(I)*2.721161Q01,' eV )'
			ENDIF
			
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1291')
			WRITE(5,'(/4X,A,A1)')TRIM(CADENA),':'
			CONT=0
			DO J=1,N
				CONT=CONT+1
				IF (CONT==1)THEN
					WRITE(5,'(4X,F11.8,2X)',ADVANCE='NO')CA(I,J)
				ELSEIF (CONT<6)THEN
					WRITE(5,'(F11.8,2X)',ADVANCE='NO')CA(I,J)
				ELSE
					WRITE(5,'(F11.8)',ADVANCE='YES')CA(I,J)
					CONT=0
				ENDIF
			ENDDO
			IF(CONT<6)WRITE(5,'(/)')
		ENDDO
			
		DO I=1,N
			IF(NOCA(I)==0)THEN
				CADENA=LEERVALOR('idioma.lng',IDIOMA,'1292')
			ELSE
				CADENA=LEERVALOR('idioma.lng',IDIOMA,'1293')
			ENDIF
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1221')
			IF (ABS(EORB(I))>500.Q0)THEN
				WRITE(5,'(/4X,A,I2,A1,1X,A,A2,F14.7,1X,A11,F11.4,A5)')TRIM(CADENA),I,':',TRIM(CADENA1),' =',EORB(I),'Hartrees ( ',EORB(I)*2.721161Q01,' eV )'
			ELSEIF (ABS(EORB(I))>2.Q0)THEN
				WRITE(5,'(/4X,A,I2,A1,1X,A,A2,F14.7,1X,A11,F10.4,A5)')TRIM(CADENA),I,':',TRIM(CADENA1),' =',EORB(I),'Hartrees ( ',EORB(I)*2.721161Q01,' eV )'
			ELSE
				WRITE(5,'(/4X,A,I2,A1,1X,A,A2,F14.7,1X,A11,F10.6,A5)')TRIM(CADENA),I,':',TRIM(CADENA1),' =',EORB(I),'Hartrees ( ',EORB(I)*2.721161Q01,' eV )'
			ENDIF
			
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1291')
			WRITE(5,'(/4X,A,A1)')TRIM(CADENA),':'
			CONT=0
			DO J=1,N
				CONT=CONT+1
				IF (CONT==1)THEN
					WRITE(5,'(4X,F11.8,2X)',ADVANCE='NO')CB(I,J)
				ELSEIF (CONT<6)THEN
					WRITE(5,'(F11.8,2X)',ADVANCE='NO')CB(I,J)
				ELSE
					WRITE(5,'(F11.8)',ADVANCE='YES')CB(I,J)
					CONT=0
				ENDIF
			ENDDO
			IF(CONT<6)WRITE(5,'(/)')
		ENDDO

		CALL SEPARADOR(78,3,1,5)
	ENDIF

	IF(ESCRITURA(10)==1)THEN	!ENERGÍAS HF Y MP2
		ENELTOT=LEERVALOR_REAL(DIR.MTD,'ENERGIAS','EnerElectr')
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1223')
		WRITE(5,'(4X,A,A,F22.15)')TRIM(CADENA),' (HF) = ',ENELTOT
		EREP=LEERVALOR_REAL(DIR.MTD,'ENERGIAS','EnerRep')
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1224')
		WRITE(5,'(4X,A,A,F22.15)')TRIM(CADENA),' = ',EREP
		ETOT=LEERVALOR_REAL(DIR.MTD,'ENERGIAS','EnerTotal')
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1225')
		WRITE(5,'(4X,A,A,F22.15)')TRIM(CADENA),' (HF) = ',ETOT
		IF (SCF=='MP2')THEN
			ECMP2=LEERVALOR_REAL(DIR.MTD,'ENERGIAS','EnerMP2')
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1226')
			WRITE(5,'(4X,A,A,F22.15)')TRIM(CADENA),' (MP2) = ',ECMP2
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1223')
			WRITE(5,'(4X,A,A,F22.15)')TRIM(CADENA),' (MP2) = ',ENEL+ECMP2
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1225')
			WRITE(5,'(4X,A,A,F22.15)')TRIM(CADENA),' (MP2) = ',ETOT+ECMP2
		ENDIF
		CALL SEPARADOR(78,3,1,5)
	ENDIF

	IF(ESCRITURA(11)==1)THEN	!VALORES MEDIOS
		TMEDIA=LEERVALOR_REAL(DIR.MTD,'ITERACIONES','Tmedia')
		VMEDIA=LEERVALOR_REAL(DIR.MTD,'ITERACIONES','Vmedia')
		
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1294')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		WRITE(5,'(/4X,A,F12.6,11X,A,F12.6)')'<T> =',TMEDIA,'<V> =',VMEDIA
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1295')
		WRITE(5,'(/4X,A,F12.6,2X,A1,A,A1)')'-<V>/<T> =',-VMEDIA/TMEDIA,'(',TRIM(CADENA),')'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1296')
		WRITE(5,'(/4X,A,F12.6,2X,A1,A,A1)')'- U /<T> =',(TMEDIA-ETOT)/TMEDIA,'(',TRIM(CADENA),')'
		
		CALL SEPARADOR(78,3,1,5)
	ENDIF

	IF(MOMENTODIPOLAR==1.AND.ESCRITURA(12)==1)THEN	!MOMENTO DIPOLAR
		PXEL=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipElecX')
		PYEL=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipElecY')
		PZEL=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipElecZ')
		PXNUC=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipNucX')
		PYNUC=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipNucY')
		PZNUC=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipNucZ')
		PX=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipTotX')
		PY=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipTotY')
		PZ=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','MomentoDipTotZ')
		PMODUL=LEERVALOR_REAL(DIR.PRP,'MOMENTODIPOLAR','ModuloMomentoDip')

		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1297')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		WRITE(5,'(4X,3(A,1X,G14.7,3X))')'X->',PXEL,'Y->',PYEL,'Z->',PZEL
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1298')
		WRITE(5,'(/4X,A,A1)')TRIM(CADENA),':'
		WRITE(5,'(4X,3(A,1X,G14.7,3X))')'X->',PXNUC,'Y->',PYNUC,'Z->',PZNUC
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1299')
		WRITE(5,'(/4X,A,A1)')TRIM(CADENA),':'
		WRITE(5,'(4X,3(A,1X,G14.7,3X))')'X->',PX,'Y->',PY,'Z->',PZ
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1241')
		WRITE(5,'(/5X,A,A1,F10.5,A,F9.5,A)')TRIM(CADENA),':',PMODUL,' U.A. (=',PMODUL*2.541765Q0,' DEBYES)'
		
		CALL SEPARADOR(78,3,1,5)
	ENDIF

	IF(POBLACIONES==1.AND.ESCRITURA(13)==1)THEN	!POBLACIONES
		DEALLOCATE(POBEL,STAT=ERROR)
		ALLOCATE (POBEL(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DEALLOCATE(POSX,STAT=ERROR)
		ALLOCATE (POSX(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DEALLOCATE(POSY,STAT=ERROR)
		ALLOCATE (POSY(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DEALLOCATE(POSZ,STAT=ERROR)
		ALLOCATE (POSZ(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DEALLOCATE(DPX,STAT=ERROR)
		ALLOCATE (DPX(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DEALLOCATE(DPY,STAT=ERROR)
		ALLOCATE (DPY(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DEALLOCATE(DPZ,STAT=ERROR)
		ALLOCATE (DPZ(1:NUC),STAT=ERROR)
		IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
		DO I=1,NUC
			POBEL(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','Poblacion('//TRIM(INTTOSTR(I))//')')
			POSX(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','PosX('//TRIM(INTTOSTR(I))//')')
			POSY(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','PosY('//TRIM(INTTOSTR(I))//')')
			POSZ(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','PosZ('//TRIM(INTTOSTR(I))//')')
			DPX(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','DespX('//TRIM(INTTOSTR(I))//')')
			DPY(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','DespY('//TRIM(INTTOSTR(I))//')')
			DPZ(I)=LEERVALOR_REAL(DIR.PRP,'POBLACIONES','DespZ('//TRIM(INTTOSTR(I))//')')
		ENDDO
		
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1300')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1243')
		WRITE(5,'(/,T5,A,T13,A,T22,A,T30,A,T39,A,T47,A,T56,A,T64,A)')TRIM(CADENA),'P(A)','X(A)','(DX)','Y(A)','(DY)','Z(A)','(DZ)'
		WRITE(5,'(T5,A,T13,A,T22,A,T30,A,T39,A,T47,A,T56,A,T64,A)') '-----','----','----','----','----','----','----','----'
		DO I=1,NUC
			WRITE(5,'(4X,I3,2X,F7.3,2X,3(F8.4,A,F6.4,A))')I,POBEL(I),POSX(I),' (',DPX(I),')',POSY(I),' (',DPY(I),')',POSZ(I),' (',DPZ(I),')'
		ENDDO

		CALL SEPARADOR(78,3,1,5)
	ENDIF

    RETURN
    END

! -------------------------------------------------------------------
! --- SUBPROGRAMA PARA ESCRIBIR DATOS Y RESULTADOS
! -------------------------------------------------------------------
	SUBROUTINE ESCR_SOLOUNA
    USE GLOBAL
	USE ESTRUCT
	CHARACTER*ILONG CADENA,CADENA1
	CHARACTER*ILONG INTTOSTR,LEERVALOR
	REAL*16 LEERVALOR_REAL
	CHARACTER*12 SPD(0:15)

	DATA SPD /'S','Px','Py','Pz','D(x²-y²)','Dxy','Dxz','Dyz','D(3z²-r²)', &
	 'F(x³-3y²x)','F(y³-3x²y)','F(x²-y²)z','Fxyz','F(xr²-5xz²)','F(yr²-5yz²)','F(5z³-3r²z)'/


	IF (ESCRITURA(0)==1)THEN	!CABEZERA
		CALL SEPARADOR(78,3,0,5)
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1250')
		WRITE(5,'(8X,A)')TRIM(CADENA)
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'116')
		WRITE(5,'(/,8X,A)')'D. ZORRILLA & M. FERNANDEZ'
		CALL SEPARADOR(78,3,0,5)
	ENDIF

	IF (ESCRITURA(1)==1)THEN	!DATOS
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1251')
		WRITE(5,'(/,4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(NUC))
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1252')
		WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(N))
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1253')
		WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(CLASMON)
		IF(CLASMON=='HAS'.OR.CLASMON=='HAL'.OR.CLASMON=='HAM'.OR.CLASMON=='RND')THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1254')
			WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(NMC))
        ELSEIF(CLASMON=='GSS')THEN
            CADENA=LEERVALOR('idioma.lng',IDIOMA,'1244')
            !NGAUSS=LEERVALOR_INT(DIR.INT,'FBASE','NumGauss')
			NGAUSS=0
            DO I=1,N
                NGAUSS=NGAUSS+FB(I).NSFB
            ENDDO
            WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(INTTOSTR(NGAUSS))
		ENDIF
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1255')
		WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(SCF)

		CALL SEPARADOR(78,1,1,5)

		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1256')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1243')
		CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1257')
		WRITE(5,'(/,T7,A,T22,A,T37,A1,T48,A1,T59,A1)')TRIM(CADENA),TRIM(CADENA1),'X','Y','Z'
		WRITE(5,'(4X,A,6X,A,6X,A)')'----------','-------','-----------------------------'
		DO I=1,NUC
			WRITE(5,'(4X,A,7X,F6.2,4X,F10.5,1X,F10.5,1X,F10.5)')TRIM(NUCLEOS(I).NOMBRE),NUCLEOS(I).CARGA,NUCLEOS(I).X,NUCLEOS(I).Y,NUCLEOS(I).Z
		ENDDO

		CALL SEPARADOR(78,1,1,5)

		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1258')
		WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1259')
		CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1260')
		WRITE(5,'(/,T6,A,T26,A,T65,A)')'N',TRIM(CADENA),TRIM(CADENA1)
		WRITE(5,'(4X,A,1X,A,3X,A)')'---','----------------------------------------------------','---------------'
		
        IF(TIPOFB==0)THEN
            WRITE(5,'(/,T6,A,T26,A,T65,A)')'N',TRIM(CADENA),TRIM(CADENA1)
		    WRITE(5,'(4X,A,1X,A,3X,A)')'---','----------------------------------------------------','---------------'
			DO I=1,N
				WRITE(5,'(4X,I3,1X,A,T67,A)')I,FB(I).NOMBRE,SPD(FB(I).NTF)
			ENDDO
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1261')
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1262')
			WRITE(5,'(/,4X,A,A1,I3,A,A1,I5)')TRIM(CADENA),':',NPOLIG,TRIM(CADENA1),':',INCREMENT+1
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1263')
			CADENA1=LEERVALOR('idioma.lng',IDIOMA,'1264')
			WRITE(5,'(4X,A,A1,F10.5,A,A1,F10.5)')TRIM(CADENA),':',INIR,TRIM(CADENA1),':',FINR
        ELSEIF(TIPOFB==1)THEN
			WRITE(5,'(/,T6,A,3X,A,T26,A,T65,A)')'N','S',TRIM(CADENA),TRIM(CADENA1)
		    WRITE(5,'(4X,A,1X,A,1X,A,3X,A)')'---','---','--------------------------------------------------','---------------'
		    DO I=1,N
				DO J=1,FB(I).NSFB
					IF(FB(I).SFB(J).PARAMETRO1==0.Q0)THEN
                        WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F8.5,A,F6.3,A,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR,' EXP(-',FB(I).SFB(J).PARAMETRO2,' r -',FB(I).SFB(J).PARAMETRO3,' R^2)',SPD(FB(I).NTF)
                    ELSE
                        WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F6.3,A,F8.5,A,F6.3,A,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR,' r^',FB(I).SFB(J).PARAMETRO1,' EXP(-',FB(I).SFB(J).PARAMETRO2,' r -',FB(I).SFB(J).PARAMETRO3,' R^2)',SPD(FB(I).NTF)
                    ENDIF
                ENDDO
            ENDDO
        ELSEIF(TIPOFB==2)THEN
            WRITE(5,'(/,T6,A,3X,A,T26,A,T65,A)')'N','S',TRIM(CADENA),TRIM(CADENA1)
		    WRITE(5,'(4X,A,1X,A,1X,A,3X,A)')'---','---','--------------------------------------------------','---------------'
			DO I=1,N
				DO J=1,FB(I).NSFB
                    IF(FB(I).SFB(J).PARAMETRO1==0.Q0)THEN
                        WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F8.5,A,F6.3,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR,' (',FB(I).SFB(J).PARAMETRO2,' - r)^',FB(I).SFB(J).PARAMETRO3,SPD(FB(I).NTF)
                    ELSE
					    WRITE(5,'(4X,I2,2X,I2,2X,G14.7,A,F6.3,A,F8.5,A,F6.3,T70,A)')I,J,FB(I).SFB(J).COEFICIENTE*FB(I).SFB(J).SCNOR,'r^',FB(I).SFB(J).PARAMETRO1,' (',FB(I).SFB(J).PARAMETRO2,' - r)^',FB(I).SFB(J).PARAMETRO3,SPD(FB(I).NTF)
                    ENDIF
                ENDDO
            ENDDO
		ENDIF
                
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1265')
		WRITE(5,'(/,4X,A,A1)')TRIM(CADENA),':'
		WRITE(5,'(/,T6,A,T15,A,T26,A,T37,A)')'N','X','Y','Z'
		WRITE(5,'(4X,A,4X,A)')'---','-----------------------------'
		DO I=1,N
			WRITE(5,'(4X,I3,1X,F10.5,1X,F10.5,1X,F10.5)')I,FB(I).X,FB(I).Y,FB(I).Z
		ENDDO

		IF(RECORT==1.OR.RECORT==2) THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1266')
			WRITE(5,'(/,4X,A,A1)')TRIM(CADENA),':'
			WRITE(5,'(/,5X,A,8X,A,14X,A)')'N','R0','D'
			WRITE(5,'(4X,A,3X,A,4X,A)')'---','-----------','-----------'
			DO I=1,N
				WRITE(5,'(4X,I3,2X,F10.5,6X,F10.5)')I,FB(I).RECOR.R1,FB(I).RECOR.D1
			END DO
		ENDIF

		CALL SEPARADOR(78,1,1,5)
		
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1267')
		WRITE(5,'(4X,A,A1,/)')TRIM(CADENA),':'
		CADENA=LEERVALOR('idioma.lng',IDIOMA,'1268')
        WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
        M=N/10
        I=1
        DO J=1,M
            WRITE(5,'(16X,10I2)')(NOCA(II),II=I,I+9)
            I=J*10+1
		ENDDO
        CADENA=LEERVALOR('idioma.lng',IDIOMA,'1269')
        WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
        I=1
        DO J=1,M
            WRITE(5,'(16X,10I2)')(NOCB(II),II=I,I+9)
            I=J*10+1
		ENDDO

		IF(POT(1)/=CERO.OR.POT(2)/=CERO.OR.POT(3)/=CERO)THEN
			CALL SEPARADOR(78,1,1,5)
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1270')
			WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
			WRITE(5,'(/,T9,A,T20,A,T31,A)')'X','Y','Z'
			WRITE(5,'(4X,A)')'-------------------------------'
			WRITE(5,'(4X,F8.4,3X,F8.4,3X,F8.4)')POT(1),POT(2),POT(3)
		ENDIF
	
		CALL SEPARADOR(78,3,1,5)
	ENDIF

	INTEGRAL=LEERVALOR_REAL(DIR.INT,'INTEGRALES','Integral')
	ERINTS=LEERVALOR_REAL(DIR.INT,'INTEGRALES','Error')
    
	CADENA=LEERVALOR('idioma.lng',IDIOMA,'1301')
	WRITE(5,'(4X,A,A1)')TRIM(CADENA),':'
	IF (CLASINT=='J'.OR.CLASINT=='j') THEN
		IF(CLASMON/='GSS'.OR.CLASMON/='GSA')THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1302')
			WRITE(5,'(5X,A1,2I3,A1,2I3,A4,G18.10,4X,A,A3,G14.6)')'(',SN1,SN2,'|',SN3,SN4,') = ',INTEGRAL,TRIM(CADENA),' = ',ERINTS
		ELSE
			WRITE(5,'(5X,A1,2I3,A1,2I3,A4,G18.10)')'(',SN1,SN2,'|',SN3,SN4,') = ',INTEGRAL
		ENDIF
	ELSE
		IF(CLASMON/='GSS'.OR.CLASMON/='GSA')THEN
			CADENA=LEERVALOR('idioma.lng',IDIOMA,'1302')
			WRITE(5,'(5X,A1,I3,A1,A1,A1,I3,A4,G18.10,4X,A,A3,G14.6)')'<',SN1,'|',CLASINT,'|',SN2,'> = ',INTEGRAL,TRIM(CADENA),' = ',ERINTS
		ELSE
			WRITE(5,'(5X,A1,I3,A1,I3,A4,G18.10)')'<',SN1,'|',CLASINT,'|',SN2,'> = ',INTEGRAL
		ENDIF
	ENDIF

	CALL SEPARADOR(78,3,1,5)

	CADENA=LEERVALOR('idioma.lng',IDIOMA,'1303')
	CADENA1=LEERVALOR(DIR.INT,'TIEMPO','TiempoIntegracion')
	WRITE(5,'(4X,A,A1,2X,A)')TRIM(CADENA),':',TRIM(CADENA1)
	CALL SEPARADOR(78,3,1,5)

	END
