!************************************************************************
!    PROGRAMA QUE DADO UNA FUNCION MATEMATICA F(R) Y UN VALOR PARA
!    LA VARIABLE R, DEVUELVE EL VALOR NUMERICO DE ESA FUNCION (REAL*16)
!	 TAMBIEN REALIZA LA DERIVADA DE LA FUNCION
!    LAS FUNCIONES MATEMATICAS PERMITIDAS SON:
!    SIN----SENO
!    COS----COSENO
!    TAN----TANGENTE
!    ASIN---ARCOSENO
!    ACOS---ARCOCOSENO
!    ATAN---ARCOTANGENTE
!    LOG----LOGARITMO EN BASE 10
!    LN-----LOGARITMO NEPERIANO
!    EXP----EXPONENCIAL (e^R)
!    ABS----VALOR ABSOLUTO
!    SQRT---RAIZ CUADRADA
!    ^------POTENCIACION (CON NUMEROS DE DOBLE PRECISION)
!************************************************************************

!************************************************************************
!     FUNCION QUE CALCULA LA FUNCION ALMACENADA PARA UN VALOR DADO
!************************************************************************
    REAL*16 FUNCTION CALCFUNC(VARIABLE,CFUN)
    USE ESTRUCT
	DIMENSION MONO(30),POLI(30)
    REAL*16 VARIABLE,MONO,POLI
    INTEGER*1 MR1,MR2,MO,MF,MOR,ML,PR1,PR2,PO,PF,POR,PL,FR1,FR2,FO,FF,FOR,FL
    REAL*16 COEF,VALOR,EXP
    INTEGER I,J,K,L,N,II
    
	RECORD /CF/CFUN

	DO I=1,CFUN.ORD
		DO J=1,CFUN.NP
			CALL DESCIFRA(CFUN.P(J),PR1,PR2,PO,PF,POR,PL)
			IF(I==POR)THEN
				DO N=1,CFUN.NVI,3
					CALL DESCIFRA(CFUN.M((N+2)/3),MR1,MR2,MO,MF,MOR,ML)
					IF(I==MOR)THEN
						IF(CFUN.VI(N)==1.Q-200)COEF=VARIABLE
						IF(CFUN.VI(N)>=1.Q-100.AND.CFUN.VI(N)<=1.Q-50)THEN
							COEF=CFUN.VI(N)/1.Q-100
							COEF=POLI(IQNINT(COEF)-96)
						END IF
						IF(CFUN.VI(N)>=1.Q-50)COEF=CFUN.VI(N)
						IF(CFUN.VI(N+1)<1.Q-200)VALOR=0.Q0
						IF(CFUN.VI(N+1)==1.Q-200)VALOR=VARIABLE
						IF(CFUN.VI(N+1)>=1.Q-100.AND.CFUN.VI(N+1)<=1.Q-50)THEN
							VALOR=CFUN.VI(N+1)/1.Q-100
							VALOR=POLI(IQNINT(VALOR)-96)
						END IF
						IF(CFUN.VI(N+1)>=1.Q-50)VALOR=CFUN.VI(N+1)
						IF(CFUN.VI(N+2)==1.Q-200)EXP=VARIABLE
						IF(CFUN.VI(N+2)>=1.Q-100.AND.CFUN.VI(N+2)<=1.Q-50)THEN
							EXP=CFUN.VI(N+2)/1.Q-100
							EXP=POLI(IQNINT(EXP)-96)
						END IF
						IF(CFUN.VI(N+2)>=1.Q-50.OR.CFUN.VI(N+2)<=0.Q0)EXP=CFUN.VI(N+2)
						!IF(CFUN.VI(N+2)==0.Q0)EXP=0.Q0	!ESTO SE DEBE A QUE CUANDO 
														!CFUN.VI==0.Q0 NO HACIA EXP=0.Q0

						MONO((N+2)/3)=COEF*(VALOR**EXP)
					END IF
				END DO
			END IF
		END DO
		DO K=1,CFUN.NP
			CALL DESCIFRA(CFUN.P(K),PR1,PR2,PO,PF,POR,PL)
			IF(I==POR)THEN
				POLI(K)=MONO(PR1)
				DO II=PR1,PR2
					CALL DESCIFRA(CFUN.M(II),MR1,MR2,MO,MF,MOR,ML)
					IF(MO==0)EXIT
					IF(MO==1)POLI(K)=POLI(K)+MONO(II+1)
					IF(MO==2)POLI(K)=POLI(K)-MONO(II+1)
					IF(MO==3)POLI(K)=POLI(K)*MONO(II+1)
					IF(MO==4)POLI(K)=POLI(K)/MONO(II+1)
				END DO
			END IF
		END DO
		DO L=1,CFUN.NF
			CALL DESCIFRA(CFUN.FU(L),FR1,FR2,FO,FF,FOR,FL)
			IF(I==FOR)THEN
				IF(FF==0)POLI(FR1)=POLI(FR1)
				IF(FF==1)POLI(FR1)=QSIN(POLI(FR1))
				IF(FF==2)POLI(FR1)=QCOS(POLI(FR1))
				IF(FF==3)POLI(FR1)=QTAN(POLI(FR1))
				IF(FF==4)POLI(FR1)=QASIN(POLI(FR1))
				IF(FF==5)POLI(FR1)=QACOS(POLI(FR1))
				IF(FF==6)POLI(FR1)=QATAN(POLI(FR1))
				IF(FF==7)POLI(FR1)=QLOG10(POLI(FR1))
				IF(FF==8)POLI(FR1)=QLOG(POLI(FR1))
				IF(FF==9)POLI(FR1)=QEXP(POLI(FR1))
				IF(FF==10)POLI(FR1)=QABS(POLI(FR1))
				IF(FF==11)POLI(FR1)=QSQRT(POLI(FR1))
			END IF
		END DO
	END DO


    CALCFUNC=POLI(CFUN.NP)

    END

!************************************************************************
!     SUBROUTINA QUE CODIFICA LAS FUNCIONES PARA SU TRATAMIENTO
!************************************************************************
	SUBROUTINE CMAT(CADENA,CFUN)
	USE ESTRUCT
    IMPLICIT REAL*16(A-H,O-Z)
    CHARACTER*(*) CADENA
    CHARACTER*ILONG CAD,CADMINMAY,SUBCADENAS(20),NCAD
    INTEGER POSINI(20),NEWPOSINI(20),POSFIN(20)
    INTEGER CONT,CONTOLD,I,J,LONGCAD,CP,FUN,BUSCAFUNCION
    
    RECORD/CF/CFUN

    CADENA=CADMINMAY(CADENA)

    NCAD=TRIM(CADENA)
    CONT=0
    CP=0
    CONTOLD=0

100 LONGCAD=LEN_TRIM(NCAD)
    CFUN.ORD=CFUN.ORD+1
    DO I=1,LONGCAD
		IF (NCAD(I:I)=='(')THEN
			DO J=I+1,LONGCAD
				IF(NCAD(J:J)=='(')EXIT
				IF(NCAD(J:J)==')')THEN
					CONT=CONT+1
					POSINI(CONT)=I
					POSFIN(CONT)=J
					SUBCADENAS(CONT)=NCAD(POSINI(CONT)+1:POSFIN(CONT)-1)
					CALL POLINOMIOS(SUBCADENAS(CONT),CFUN)
					
					IF(POSINI(CONT)-4==0)THEN
						CAD=' '//NCAD(1:POSFIN(CONT))
					ELSEIF(POSINI(CONT)-4==-1)THEN
						CAD='  '//NCAD(1:POSFIN(CONT))
					ELSEIF(POSINI(CONT)-4<-1)THEN
						CAD=NCAD(1:POSFIN(CONT))
					ELSE
						CAD=NCAD(POSINI(CONT)-4:POSFIN(CONT))
					ENDIF
					!CAD=NCAD(POSINI(CONT)-4:POSFIN(CONT))

					CALL FUNCIONES(CAD,NEWPOSINI(CONT),CFUN)
					IF(NEWPOSINI(CONT)/=0)CFUN.FU(CFUN.NF)=CFUN.FU(CFUN.NF)+CFUN.NP+CFUN.ORD*16777216
				    NEWPOSINI(CONT)=NEWPOSINI(CONT)+POSINI(CONT)
					CP=CP-1
					EXIT
				END IF
			END DO
			CP=CP+1
		END IF
    END DO

    IF (CONT==0)THEN !CASO SIN NINGUN PARENTESIS
		CONT=1
		POSINI(CONT)=1
		POSFIN(CONT)=LEN_TRIM(NCAD)
		SUBCADENAS(CONT)=CADENA(POSINI(CONT):POSFIN(CONT))
		CALL POLINOMIOS(SUBCADENAS(CONT),CFUN)
		RETURN
    END IF

    CALL SUBSTCADENA(NCAD,NEWPOSINI,POSFIN,CONT,CONTOLD)
    CONTOLD=CONT

    IF(CP/=0)THEN
		CP=0
		GOTO 100
    ELSE
		CFUN.ORD=CFUN.ORD+1
		CALL POLINOMIOS(NCAD,CFUN)
    END IF

    END

!************************************************************************
!       FUNCION QUE NOS DICE SI HAY ALGUNA FUNCION TRIGONOMETRICA,
!       EXPONENCIAL,LOGARITMICA,CICLOMETRICA,...,EN LA CADENA Y NOS
!       DA LA POSICION INICIAL DE LA FUNCION (INI).
!
!       LOS CODIGOS DE LAS FUNCIONES MATEMATICAS SON:
!        SIN----SENO------------------1
!        COS----COSENO----------------2
!        TAN----TANGENTE--------------3
!        ASIN---ARCOSENO--------------4
!        ACOS---ARCOCOSENO------------5
!        ATAN---ARCOTANGENTE----------6
!        LOG----LOGARITMO EN BASE 10--7
!        LN-----LOGARITMO NEPERIANO---8
!        EXP----EXPONENCIAL (e^R)-----9
!        ABS----VALOR ABSOLUTO--------10
!        SQRT---RAIZ CUADRADA---------11
!
!     NOTA: ESTOS CODIGOS ESTAN EN LOS 4 ULTIMOS BITS DEL TERCER BYTE 
!			EN UN INTEGER*4
!************************************************************************
	SUBROUTINE FUNCIONES(CADENA,INI,FF)
    USE ESTRUCT
	CHARACTER*(*) CADENA
    INTEGER INI,COINCIDE
	
	RECORD/CF/FF

    INI=0
    COINCIDE=0

    COINCIDE=INDEX(CADENA(2:4),'SIN')
    IF(COINCIDE/=0.AND.CADENA(1:1)/='A')THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*1
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-3
    END IF
    COINCIDE=INDEX(CADENA(2:4),'COS')
    IF(COINCIDE/=0.AND.CADENA(1:1)/='A')THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*2
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-3
    END IF
    COINCIDE=INDEX(CADENA(2:4),'TAN')
    IF(COINCIDE/=0.AND.CADENA(1:1)/='A')THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*3
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-3
    END IF
    COINCIDE=INDEX(CADENA(1:4),'ASIN')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*4
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-4
	END IF
    COINCIDE=INDEX(CADENA(1:4),'ACOS')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*5
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-4
    END IF
    COINCIDE=INDEX(CADENA(1:4),'ATAN')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*6
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-4
    END IF
    COINCIDE=INDEX(CADENA(2:4),'LOG')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*7
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-3
    END IF
    COINCIDE=INDEX(CADENA(3:4),'LN')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*8
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-2
    END IF
    COINCIDE=INDEX(CADENA(2:4),'EXP')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*9
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-3
    END IF
    COINCIDE=INDEX(CADENA(2:4),'ABS')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*10
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-3
	END IF
    COINCIDE=INDEX(CADENA(1:4),'SQRT')
    IF(COINCIDE/=0)THEN
		FF.NF=FF.NF+1
		FF.FU(FF.NF)=1048576*11
		FF.FU(FF.NF)=FF.FU(FF.NF)+FF.NF*268435456
		INI=-4
	END IF

    END

!************************************************************************
!     FUNCION QUE TOMA UNA CADENA DE CARACTERES (POLINOMIO)
!     Y DEVUELVE UNA MATRIZ DE VALORES Y CODIGOS PARA PODER CALCULAR
!     SU VALOR NUMERICO
!************************************************************************
    SUBROUTINE POLINOMIOS(POLINOM,FF)
	USE ESTRUCT
    IMPLICIT REAL*16(A-H,O-Z)
    CHARACTER*(*) POLINOM
    CHARACTER*ILONG SUBPOLIN(20),CAD1
    INTEGER I,J,CONT,LONG
    INTEGER POSINI(20),POSFIN(20)
    INTEGER*4 CIFRA
    INTEGER*1 OP,NMINI

    RECORD/CF/FF

    NMINI=FF.NM+1

    LONG=LEN_TRIM(POLINOM)
    CONT=0
    POSINI(1)=1
    DO J=1,LONG
		IF (POLINOM(J:J)=='+'.OR.POLINOM(J:J)=='-'.OR.POLINOM(J:J)=='/')THEN
			CONT=CONT+1
			FF.NM=FF.NM+1
			POSINI(CONT+1)=J+1
			POSFIN(CONT)=J-1
			IF(J==1)THEN
				SUBPOLIN(CONT)='0'
			ELSE
				SUBPOLIN(CONT)=POLINOM(POSINI(CONT):POSFIN(CONT))
			END IF
			IF (POLINOM(J:J)=='+')OP=1
			IF (POLINOM(J:J)=='-')OP=2
			IF (POLINOM(J:J)=='*')OP=3
			IF (POLINOM(J:J)=='/')OP=4
			FF.M(FF.NM)=CIFRA(FF.NM,INT1(FF.NM+1),OP,INT1(0),FF.ORD,INT1(0))
		END IF
    END DO
    CONT=CONT+1
    FF.NM=FF.NM+1
    POSFIN(CONT)=LONG
    SUBPOLIN(CONT)=POLINOM(POSINI(CONT):POSFIN(CONT))
    FF.M(FF.NM)=CIFRA(FF.NM,FF.NM,INT1(0),INT1(0),FF.ORD,INT1(0))

    DO I=1,CONT
		CAD1=SUBPOLIN(I)
		CALL MONOMIOS(CAD1,FF)
    END DO

    FF.NP=FF.NP+1
    FF.P(FF.NP)=CIFRA(NMINI,FF.NM,INT1(0),INT1(0),FF.ORD,INT1(0))
    FF.P(FF.NP)=FF.P(FF.NP)+FF.NP*268435456

    END

!************************************************************************
!       SUBROUTINA QUE CODIFICA LOS MONOMIOS
!************************************************************************
    SUBROUTINE MONOMIOS(CADENA,FF)
	USE ESTRUCT
    IMPLICIT REAL*16(A-H,O-Z)
    CHARACTER*(*) CADENA
	CHARACTER*ILONG CADCOEF,CAQEXP,CADVALOR
    REAL*16 COEFICIENTE,EXPONENTE,VALOR 
    INTEGER BUSCA,POSPOR,POSDIV,POSELEVA
    CHARACTER*1 CAR
      
	RECORD/CF/FF

    LONGCAD=LEN_TRIM(CADENA)

    POSELEVA=BUSCA(CADENA,'^',0,1,1)
    POSPOR=BUSCA(CADENA,'*',0,1,1)
    POSDIV=BUSCA(CADENA,'/',0,1,1)

    COEFICIENTE=0.Q0
    VALOR=0.Q0
    EXPONENTE=0.Q0

	IF (POSDIV/=0)THEN
		WRITE(*,*)'ERROR EN LA FUNCION'
		STOP
    ELSE
		IF(POSELEVA/=0)THEN
			IF(POSPOR/=0)THEN
				CADCOEF=CADENA(1:POSPOR-1)
				CADVALOR=CADENA(POSPOR+1:POSELEVA-1)
				CAQEXP=CADENA(POSELEVA+1:LONGCAD)
			ELSE
				CAQEXP=CADENA(POSELEVA+1:LONGCAD)
				CADVALOR=CADENA(1:POSELEVA-1)
				CADCOEF='1'
			END IF
		ELSE
			IF(POSPOR/=0)THEN
				CADCOEF=CADENA(1:POSPOR-1)
				CADVALOR=CADENA(POSPOR+1:LONGCAD)
				CAQEXP='1'
			ELSE
				CADVALOR=CADENA
				CADCOEF='1'
				CAQEXP='1'
			END IF
		END IF
    END IF

    CAR=CADCOEF(1:1)
    SELECT CASE (CAR)
		CASE ('a':'q','s':'z')
			COEFICIENTE=ICHAR(CAR)*1.Q-100
		CASE ('R')
		    COEFICIENTE=1.Q-200
		CASE DEFAULT
			READ(CADCOEF,*)COEFICIENTE
	END SELECT
    CAR=CAQEXP(1:1)
    SELECT CASE (CAR)
		CASE ('a':'q','s':'z')
			EXPONENTE=ICHAR(CAR)*1.Q-100
		CASE ('R')
		    EXPONENTE=1.Q-200
		CASE DEFAULT
			READ(CAQEXP,*)EXPONENTE
	END SELECT
    CAR=CADVALOR(1:1)
    SELECT CASE (CAR)
		CASE ('a':'q','s':'z')
			VALOR=ICHAR(CAR)*1.Q-100
		CASE ('R')
		    VALOR=1.Q-200
		CASE DEFAULT
			READ(CADVALOR,*)VALOR
	END SELECT

	FF.NVI=FF.NVI+1
    FF.VI(FF.NVI)=COEFICIENTE
    FF.NVI=FF.NVI+1
    FF.VI(FF.NVI)=VALOR
    FF.NVI=FF.NVI+1
    FF.VI(FF.NVI)=EXPONENTE

    END

!************************************************************************
!   FUNCION QUE DEVUELVE LA CADENA CON LAS SUSTITUCIONES DE VARIABLES
!************************************************************************
    SUBROUTINE SUBSTCADENA(NEWCADENA,POSINI,POSFIN,CONT,C1)
	USE ESTRUCT
    IMPLICIT REAL*16(A-H,O-Z)
    CHARACTER*(*) NEWCADENA
    INTEGER POSINI(20),POSFIN(20),NEWPOSINI(20),NEWPOSFIN(20)
    INTEGER LONGCAD,CONT,C1

    LONGCAD=LEN_TRIM(NEWCADENA)

    DO K=1,CONT
		NEWPOSINI(K)=POSINI(K)
		NEWPOSFIN(K)=POSFIN(K)
    END DO

	DO I=C1+1,CONT
		DO J=1,LONGCAD
			IF(J==POSINI(I))THEN
				NEWCADENA=NEWCADENA(1:NEWPOSINI(I)-1)//CHAR(I+96)//NEWCADENA(NEWPOSFIN(I)+1:LONGCAD)
				INCR=POSFIN(I)-POSINI(I)
				DO K=I+1,CONT
					NEWPOSINI(K)=NEWPOSINI(K)-INCR
					NEWPOSFIN(K)=NEWPOSFIN(K)-INCR
				END DO
			END IF
		END DO
    END DO

    END

!************************************************************************
!   FUNCION QUE COMPRUEBA SI EL PARENTESIS ELEGIDO YA ESTABA USADO
!************************************************************************
    INTEGER FUNCTION COMP(DATO,POS)
    INTEGER DATO
    INTEGER POS(20)

    DO I=1,20
	   IF(DATO==POS(I))THEN
			COMP=1
			EXIT
       END IF
       COMP=0
    END DO

    END

!************************************************************************
!       FUNCION QUE NOS DICE SI HAY ALGUNA FUNCION TRIGONOMETRICA,
!       EXPONENCIAL,LOGARITMICA,CICLOMETRICA,...,EN LA CADENA Y NOS
!       DEVUELVE 1 SI LA HAY Y CERO SI NO LA HAY
!************************************************************************
    INTEGER FUNCTION BUSCAFUNCION(CADENA)
	CHARACTER*(*) CADENA

    BUSCAFUNCION=INDEX(CADENA,'SIN')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'COS')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'TAN')
    IF(BUSCAFUNCION/=0)RETURN
!    BUSCAFUNCION=INDEX(CADENA,'SEC')
!    IF(BUSCAFUNCION/=0)RETURN
!    BUSCAFUNCION=INDEX(CADENA,'COSEC')
!    IF(BUSCAFUNCION/=0)RETURN
!    BUSCAFUNCION=INDEX(CADENA,'COTAN')
!    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'ASIN')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'ACOS')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'ATAN')
    IF(BUSCAFUNCION/=0)RETURN
!    BUSCAFUNCION=INDEX(CADENA,'ASEC')
!    IF(BUSCAFUNCION/=0)RETURN
!    BUSCAFUNCION=INDEX(CADENA,'ACOSEC')
!    IF(BUSCAFUNCION/=0)RETURN
!    BUSCAFUNCION=INDEX(CADENA,'ACOTAN')
!    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'EXP')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'LN')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'LOG')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'ABS')
    IF(BUSCAFUNCION/=0)RETURN
    BUSCAFUNCION=INDEX(CADENA,'SQRT')
    IF(BUSCAFUNCION/=0)RETURN

    BUSCAFUNCION=0

    END

!**********************************************************************
!     SUBROUTINA QUE DESCIFRA UN INTEGER*4 DE LA SIGUIENTE FORMA:
!     -EL PRIMER BYTE NOS DA UN NUMERO ENTRE 0 Y 255 (VALOR DEL 1ER. N§)
!     -EL SEGUNDO BYTE NOS DA UN NUMERO ENTRE 0 Y 255 (VALOR DEL 2DO. N§)
!     -LA MITAD TERCERO EL CODIGO DE LA OPERACION A REALIZAR(+,-,*,/)
!     -LA OTRA MITAD DEL TERCERO EL TIPO DE FUNCION HAY QUE APLICAR
!     -LA MITAD DEL CUARTO NOS DA EL ORDEN EN EL QUE SE DEBE HACER LA OPERACION
!     -LA OTRA MITAD DEL CUARTO NOS DA LA LETRA ASIGNADA SI ES UNA FUNCION
!**********************************************************************
    SUBROUTINE DESCIFRA(I,R1,R2,O,F,ORD,LE)
    INTEGER*4 I,J,K,L,M,N
    INTEGER*1 R1,R2,O,F,ORD,LE

    R1=IAND(I,255)
    J=ISHC(I,-8)
    R2=IAND(J,255)
    K=ISHC(J,-8)
    O=IAND(K,15)
    L=ISHC(K,-4)
    F=IAND(L,15)
    M=ISHC(L,-4)
    ORD=IAND(M,15)
    N=ISHC(M,-4)
    LE=IAND(N,15)
    LE=LE+96

    END

!**********************************************************************
!     SUBROUTINA QUE CIFRA UN INTEGER*4 DE LA SIGUIENTE FORMA:
!     NUMERO=268435456*(VALOR DE LOS 4 ULTIMOS BITS DEL 4§ BYTE)+
!        16777216*(VALOR DE LOS 4§PRIMEROS BITS)+1048576*(VALOR DE LOS
!        4 ULTIMOS BITS DEL 3§ BYTE)+65536*(VALOR DE LOS 4 PRIMEROS BITS
!        DEL 3§ BYTE)+256*(VALOR DEL 2§ BYTE)+(VALOR DEL 1§ BYTE)
!**********************************************************************
    INTEGER*4 FUNCTION CIFRA(R1,R2,O,F,ORD,L)
    INTEGER*1 R1,R2,O,F,ORD,L

    L=L-96
    CIFRA=268435456*INT4(L)+16777216*INT4(ORD)+1048576*INT4(F)+65536*INT4(O)+256*INT4(R2)+INT4(R1)

    END

!************************************************************************
!       SUBROUTINA QUE BUSCA UN CARACTER ANTERIOR (DIRECCION=-1)
!       O POSTERIOR (DIRECCION=1) EN UNA CADENA DADA.
!       DEVUELVE LA POSICION DEL CARACTER DENTRO DE LA CADENA
!       O BIEN DEVUELVE CERO SI NO ESTA EN LA CADENA.
!       SALTA NOS DICE EL NUMERO DE VECES QUE DEBE SALTAR ESE CARACTER
!************************************************************************
    INTEGER FUNCTION  BUSCA(CADENA,CAR,POSINI,DIRECCION,SALTO)
	USE ESTRUCT
    CHARACTER*(*) CADENA
	CHARACTER*1 MINMAY
    CHARACTER CAR
    CHARACTER*1 CARACT(ILONG)
    INTEGER POSINI,DIRECCION,SALTO,SALTA
    INTEGER I,LONGCAD

    SALTA=SALTO
    
    LONGCAD=LEN(CADENA)
    DO I=1,LONGCAD
		CARACT(I)=CADENA(I:I)
    END DO

    IF (DIRECCION==1)THEN
		DO I=POSINI+1,LONGCAD
			IF (CARACT(I)==MINMAY(CAR))THEN
				SALTA=SALTA-1
				IF(SALTA==0)THEN
					BUSCA=I
					EXIT
				END IF
			ELSE
				BUSCA=0
			END IF
		END DO
    END IF
    IF(DIRECCION==-1)THEN
		DO I=POSINI-1,1,-1
			IF (CARACT(I)==CAR)THEN
				SALTA=SALTA-1
				IF(SALTA==0)THEN
					BUSCA=I
					EXIT
				END IF
			ELSE
				BUSCA=0
			END IF
		END DO
    END IF
    END

!************************************************************************
!       SUBROUTINA QUE CONVIERTE MINUSCULAS A MAYUSCULAS UN CARACTER
!************************************************************************
    CHARACTER*1 FUNCTION MINMAY(CAR)
    INTEGER*1 ICAR
    CHARACTER*1 CAR

    ICAR=ICHAR(CAR)
	
	IF (ICAR<32.OR.ICAR>127)CAR=CHAR(32)

    IF(ICAR>=97.AND.ICAR<=122)THEN
		MINMAY=CHAR(ICAR-32)
    ELSE
		MINMAY=CHAR(ICAR)
    END IF

    END

!************************************************************************
!       SUBROUTINA QUE CONVIERTE MINUSCULAS A MAYUSCULAS UNA CADENA
!       Y QUITA LOS ESPACIOS EN BLANCO INTERCALADOS EN UNA CADENA
!************************************************************************
    CHARACTER*(*) FUNCTION CADMINMAY(CADENA)
	USE ESTRUCT
	CHARACTER*(*) CADENA
	CHARACTER*ILONG CAD
	CHARACTER*1 MINMAY
    INTEGER LONGCAD,CONT

	CONT=0
	CAD=""
    LONGCAD=LEN(CADENA)
	
	DO I=1,LONGCAD
		IF (CADENA(I:I)==' ')THEN
			CONT=CONT+1
		ELSE 
			CAD(I-CONT:I-CONT)=MINMAY(CADENA(I:I))
			!CAD=CAD(:I-CONT-1) // MINMAY(CADENA(I:I)) // CAD(I-CONT+1:)
		ENDIF
    END DO
	CADMINMAY=CAD

    END