! ------------------------------------------------------------------
! --- SUBRUTINA QUE LEE LAS INTEGRALES DE UN ARCHIVO .INT
! ------------------------------------------------------------------
    SUBROUTINE LEERINT(CLSM,FICHERO,MAT,NUMINT)
	USE ESTRUCT
	USE GLOBAL
	
	CHARACTER*(*) FICHERO
	CHARACTER*ILONG LEERVALOR,CADIDIOMA,CAD
	INTEGER*4 MAT,NUMINT
	INTEGER*4 I
	LOGICAL COMPARA,COMPARACION
	CHARACTER*3 CLSM

    IDIOMA=LEERVALOR('idioma.lng','Idioma','Idioma')
	
    CALL DEFINE_FICH(FICH.DAT,DIR.DAT,TRIM(FICHERO),'DAT')
    CALL LEEDAT() !LECTURA DEL FICHEO DE DATOS
	CALL DEFINE_FICH(FICH.INT,DIR.INT,FICH.INT,'INT')
	CALL DEFINE_FICH(FICH.SCR,DIR.SCR,TRIM(FICHERO),'SCR')

    COMPARACION=COMPARA()
        
	IF (COMPARACION==.FALSE.)THEN
		CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1320')
		CAD=' '
		CALL MENSAJES(CADIDIOMA,CAD,1.Q0)
		STOP
    ELSE
    	CALL LEEINT(MAT,NUMINT)
	ENDIF
	
	CLSM=CLASMON

	RETURN
    END

! --------------------------------------------------------------------
! --- SUBRUTINA QUE COMPARA SI LOS DATOS DEL FICHERO DE DATOS
! --- Y DEL FICHERO DE INTEGRALES SON LOS MISMOS
! --------------------------------------------------------------------
	LOGICAL FUNCTION COMPARA()
	USE GLOBAL
	USE ESTRUCT
	INTEGER*4 I,LEERVALOR_INT,NVAR
	REAL*16 LEERVALOR_REAL,VAR
	CHARACTER*ILONG LEERVALOR,CVAR,INTTOSTR,REALTOSTR

	COMPARA=.TRUE.

	NVAR=LEERVALOR_INT(DIR.INT,'CENTROS','NumCentros')
	IF(NCENTROS/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF

	DO I=1,NCENTROS
		VAR=LEERVALOR_REAL(DIR.INT,'CENTROS','Centro('//TRIM(INTTOSTR(I))//',X)')
		IF(CENTROS(I).X/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'CENTROS','Centro('//TRIM(INTTOSTR(I))//',Y)')
		IF(CENTROS(I).Y/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'CENTROS','Centro('//TRIM(INTTOSTR(I))//',Z)')
		IF(CENTROS(I).Z/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
	ENDDO

	NVAR=LEERVALOR_INT(DIR.INT,'NUCLEOS','Nucleos')
	IF(NUC/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF

	DO I=1,NUC
		NVAR=LEERVALOR_INT(DIR.INT,'NUCLEOS','Atomo('//TRIM(INTTOSTR(I))//',Centro)')
		IF(NUCLEOS(I).NC/=NVAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'NUCLEOS','Atomo('//TRIM(INTTOSTR(I))//',Znuc)')
		IF(NUCLEOS(I).CARGA/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
	ENDDO

	NVAR=LEERVALOR_INT(DIR.INT,'FBASE','NumFB')
	IF(N/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF

	NVAR=LEERVALOR_INT(DIR.INT,'FBASE','TipoFB')
	IF(TIPOFB/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF

	NVAR=LEERVALOR_INT(DIR.INT,'FBASE','Recortadas')
	IF(RECORT/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
    ENDIF

	!NVAR=LEERVALOR_INT(DIR.INT,'FBASE','NumGauss')
	!IF(NGAUSS/=NVAR)THEN
	!	COMPARA=.FALSE.
	!	RETURN
	!ENDIF

	DO I=1,N
		NVAR=LEERVALOR_INT(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',Centro)')
        IF(FB(I).NC/=NVAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		NVAR=LEERVALOR_INT(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',ParteAngular)')
        IF(FB(I).NTF/=NVAR)THEN
			COMPARA=.FALSE.
			RETURN
        ENDIF
        DO J=1,FB(I).NSFB
		    VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',coeficiente)')
		    IF(FB(I).SFB(J).COEFICIENTE/=VAR)THEN
			    COMPARA=.FALSE.
			    RETURN
            ENDIF
		    VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',parametro1)')
		    IF(FB(I).SFB(J).PARAMETRO1/=VAR)THEN
			    COMPARA=.FALSE.
			    RETURN
            ENDIF
            VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',parametro2)')
		    IF(FB(I).SFB(J).PARAMETRO2/=VAR)THEN
			    COMPARA=.FALSE.
			    RETURN
            ENDIF
            VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',parametro3)')
		    IF(FB(I).SFB(J).PARAMETRO3/=VAR)THEN
			    COMPARA=.FALSE.
			    RETURN
            ENDIF
        ENDDO
		CVAR=LEERVALOR(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',Formula)')
		IF(FB(I).NOMBRE/=CVAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',RadioCorte1)')
		IF(FB(I).RECOR.R1/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',AnchuraCorte1)')
		IF(FB(I).RECOR.D1/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',RadioCorte0)')
		IF(FB(I).RECOR.R0/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
		VAR=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',AnchuraCorte0)')
		IF(FB(I).RECOR.D0/=VAR)THEN
			COMPARA=.FALSE.
			RETURN
		ENDIF
    ENDDO

    CLASMON=LEERVALOR(DIR.INT,'METODOINTEGRACION','Metodo') !ESTE LO CAMBIA PARA CONTINUAR EL CALCULO
	!IF(CLASMON/=CVAR)THEN
	!	COMPARA=.FALSE.
	!	RETURN
	!ENDIF
	NVAR=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','NumeroPuntos')
	IF(NMC/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
    ENDIF
	NVAR=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','Semilla')
	IF(ISEM/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF

	NVAR=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','FPeso(NPolig)')
	IF(NPOLIG/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF
	VAR=LEERVALOR_REAL(DIR.INT,'METODOINTEGRACION','FPeso(Inicio)')
	IF(INIR/=VAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF
	VAR=LEERVALOR_REAL(DIR.INT,'METODOINTEGRACION','FPeso(Fin)')
	IF(FINR/=VAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF
	NVAR=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','FPeso(Incremento)')-1
	IF(INCREMENT/=NVAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF
	VAR=LEERVALOR_REAL(DIR.INT,'POTENCIALEXT','Potencial(X)')
	IF(POT(1)/=VAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF
	VAR=LEERVALOR_REAL(DIR.INT,'POTENCIALEXT','Potencial(Y)')
	IF(POT(2)/=VAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF
	VAR=LEERVALOR_REAL(DIR.INT,'POTENCIALEXT','Potencial(Z)')
	IF(POT(3)/=VAR)THEN
		COMPARA=.FALSE.
		RETURN
	ENDIF

	END

! --------------------------------------------------------------------
! --- SUBRUTINA QUE LEE LAS INTEGRALES EN EL FICHERO DE INTEGRALES ---
! --------------------------------------------------------------------
	SUBROUTINE LEEDATINT(MAT,NUMINT)
    USE GLOBAL
	USE ESTRUCT
	INTEGER*4 MAT,NUMINT
	CHARACTER*ILONG LEERVALOR,INTTOSTR
	INTEGER*4 LEERVALOR_INT
	REAL*16 LEERVALOR_REAL
	INTEGER*4 INPQ_F

	MAT=LEERVALOR_INT(DIR.INT,'DATOS','Matrices')
	NUMINT=LEERVALOR_INT(DIR.INT,'DATOS','NumeroIntegrales')
	
	NCENTROS=LEERVALOR_INT(DIR.INT,'CENTROS','NumCentros')
	DO I=1,NCENTROS
		CENTROS(I).X=LEERVALOR_REAL(DIR.INT,'CENTROS','Centro('//TRIM(INTTOSTR(I))//',X)')
		CENTROS(I).Y=LEERVALOR_REAL(DIR.INT,'CENTROS','Centro('//TRIM(INTTOSTR(I))//',Y)')
		CENTROS(I).Z=LEERVALOR_REAL(DIR.INT,'CENTROS','Centro('//TRIM(INTTOSTR(I))//',Z)')
	ENDDO

	NUC=LEERVALOR_INT(DIR.INT,'NUCLEOS','Nucleos')
	DO I=1,NUC
		NUCLEOS(I).NC=LEERVALOR_INT(DIR.INT,'NUCLEOS','Atomo('//TRIM(INTTOSTR(I))//',Centro)')
		NUCLEOS(I).X=CENTROS(NUCLEOS(I).NC).X
		NUCLEOS(I).Y=CENTROS(NUCLEOS(I).NC).Y
		NUCLEOS(I).Z=CENTROS(NUCLEOS(I).NC).Z
		NUCLEOS(I).CARGA=LEERVALOR_REAL(DIR.INT,'NUCLEOS','Atomo('//TRIM(INTTOSTR(I))//',Znuc)')
	ENDDO

	N=LEERVALOR_INT(DIR.INT,'FBASE','NumFB')
	TIPOFB=LEERVALOR_INT(DIR.INT,'FBASE','TipoFB')
	RECORT=LEERVALOR_INT(DIR.INT,'FBASE','Recortadas')
	NGAUSS=LEERVALOR_INT(DIR.INT,'FBASE','NumGauss')
	DO I=1,N
		FB(I).N_FBASE=I
		FB(I).NC=LEERVALOR_INT(DIR.DAT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',Centro)')
		FB(I).X=CENTROS(FB(I).NC).X
		FB(I).Y=CENTROS(FB(I).NC).Y
		FB(I).Z=CENTROS(FB(I).NC).Z
		FB(I).NTF=LEERVALOR_INT(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',ParteAngular')
        DO J=1,FB(I).NSFB
            FB(I).SFB(J).COEFICIENTE=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',Coeficiente)')
            FB(I).SFB(J).PARAMETRO1=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',Parametro1)')
            FB(I).SFB(J).PARAMETRO2=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',Parametro2)')
            FB(I).SFB(J).PARAMETRO3=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//',Parametro3)')
        ENDDO
		FB(I).NOMBRE=LEERVALOR(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',Formula)')
		FB(I).RECOR.R0=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',RadioCorte0)')
		FB(I).RECOR.D0=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',AnchuraCorte0)')
		FB(I).RECOR.R1=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',RadioCorte1)')
		FB(I).RECOR.D1=LEERVALOR_REAL(DIR.INT,'FBASE','FBase('//TRIM(INTTOSTR(I))//',AnchuraCorte1)')
	ENDDO

	CLASMON=LEERVALOR(DIR.INT,'METODOINTEGRACION','Metodo')
	NMC=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','NumeroPuntos')
	ISEM=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','Semilla')
	NPOLIG=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','FPeso(NPolig)')
	INIR=LEERVALOR_REAL(DIR.INT,'METODOINTEGRACION','FPeso(Inicio)')
	FINR=LEERVALOR_REAL(DIR.INT,'METODOINTEGRACION','FPeso(Fin)')
	INCREMET=LEERVALOR_INT(DIR.INT,'METODOINTEGRACION','FPeso(Incremento)')-1

	POT(1)=LEERVALOR_REAL(DIR.INT,'POTENCIALEXT','Potencial(X)')
	POT(2)=LEERVALOR_REAL(DIR.INT,'POTENCIALEXT','Potencial(Y)')
	POT(3)=LEERVALOR_REAL(DIR.INT,'POTENCIALEXT','Potencial(Z)')

	IF (MAT==0)RETURN

	DO I=1,N
		FB(I).ANOR=LEERVALOR_REAL(DIR.INT,'NORMALIZACIONTotal','N('//TRIM(INTTOSTR(I))//')')
	ENDDO
	
	DO I=1,N
		DO J=1,N
			S(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'SOLAPAMIENTO','S('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
		ENDDO
	ENDDO
	ESMED=LEERVALOR_REAL(DIR.INT,'SOLAPAMIENTO','ERRORMED')
	ESMAX=LEERVALOR_REAL(DIR.INT,'SOLAPAMIENTO','ERRORMAX')
	
	IF(MAT==1)RETURN

	DO I=1,N
		DO J=1,N
			T(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'CINETICA','T('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			V(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'POTENCIAL','V('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			H(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'ENERGIA','H('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
		ENDDO
	ENDDO
	ETMED=LEERVALOR_REAL(DIR.INT,'CINETICA','ERRORMED')
	ETMAX=LEERVALOR_REAL(DIR.INT,'CINETICA','ERRORMAX')
	EVMED=LEERVALOR_REAL(DIR.INT,'POTENCIAL','ERRORMED')
	EVMAX=LEERVALOR_REAL(DIR.INT,'POTENCIAL','ERRORMAX')
	EHMED=LEERVALOR_REAL(DIR.INT,'ENERGIA','ERRORMED')
	EHMAX=LEERVALOR_REAL(DIR.INT,'ENERGIA','ERRORMAX')

    IF(MAT==2)RETURN 

	DO I=1,N
		DO J=1,N
			XMAT(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'MOMENTOX','X('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			YMAT(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'MOMENTOY','Y('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			ZMAT(INPQ_F(I,J))=LEERVALOR_REAL(DIR.INT,'MOMENTOZ','Z('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
		ENDDO
	ENDDO
	EXMED=LEERVALOR_REAL(DIR.INT,'MOMENTOX','ERRORMED')
	EXMAX=LEERVALOR_REAL(DIR.INT,'MOMENTOX','ERRORMAX')
	EYMED=LEERVALOR_REAL(DIR.INT,'MOMENTOY','ERRORMED')
	EYMAX=LEERVALOR_REAL(DIR.INT,'MOMENTOY','ERRORMAX')
	EZMED=LEERVALOR_REAL(DIR.INT,'MOMENTOZ','ERRORMED')
	EZMAX=LEERVALOR_REAL(DIR.INT,'MOMENTOZ','ERRORMAX')
	
    IF(MAT==3)RETURN

! ------- LECTURA DE LAS INTEGRALES BIELECTRONICAS: ------
    
	DO K=1,NUMINT	
		CALL IND_PQRS(K,IP,IQ,IR,IS)
		R(K)=LEERVALOR_REAL(DIR.INT,'BIELECTRONICA','R('//TRIM(INTTOSTR(IP))//','//TRIM(INTTOSTR(IQ))//','//TRIM(INTTOSTR(IR))//','//TRIM(INTTOSTR(IS))//')')
	ENDDO
    ERMED=LEERVALOR_REAL(DIR.INT,'BIELECTRONICA','ERRORMED')
	ERMAX=LEERVALOR_REAL(DIR.INT,'BIELECTRONICA','ERRORMAX')
	
    RETURN 
    END

