!--------------------------------------------------------------------- 
! -------	    PROGRAMA "OMCM" VERSION 2.0 	 (ABRIL-2017)
! ---------------------------------------------------------------------
! -------  D. ZORRILLA, J. SÁNCHEZ, R. RODRIGUEZ,  M. FERNANDEZ 
! ---------------------------------------------------------------------

PROGRAM OMCM
	USE ESTRUCT
	USE GLOBAL
    USE IFPORT
    
	
	CHARACTER*ILONG FICHD,FICHDD
	INTEGER*2 AN1,STATUS
	INTEGER*4 COUNT
	CHARACTER*ILONG BUF
	REAL*8 S1,S2,S3,SEG
	INTEGER*4 DIAS,HOR,MIN
	CHARACTER*ILONG TT
	INTEGER*4 MAT,NUMINT
	CHARACTER*ILONG INTTOSTR,REAL8TOSTR,LEERVALOR
	INTEGER*4 LEERVALOR_INT
	CHARACTER*ILONG CADIDIOMA

	IDIOMA=LEERVALOR('idioma.lng','Idioma','Idioma')

! ---- NOMBRE DEL FICHERO DE DATOS :
	COUNT=NARGS( )
	IF (COUNT==1) THEN
		CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1200')
		WRITE(*,'(A)')TRIM(CADIDIOMA)
		CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1201')
		WRITE(*,'(A)')TRIM(CADIDIOMA)
		READ(*,*)FICHD
	ELSEIF (COUNT==2) THEN
		AN1=INT2(COUNT-1)
		CALL GETARG(AN1, BUF, STATUS)
		FICHD=BUF
	ENDIF

! ---- FILE Y DIRECTORIO DEL FICHERO DE DATOS, SCF Y LEE EL NOMBRE DEL FICHERO DE INTEGRALES	
	CALL DEFINE_FICH(FICH.SCR,DIR.SCR,FICHD,'SCR')
	CALL DEFINE_FICH(FICH.DAT,DIR.DAT,FICHD,'DAT')
	CALL DEFINE_FICH(FICH.MTD,DIR.MTD,FICHD,'MTD')
	CLASMON=LEERVALOR(DIR.DAT,'METODOINTEGRACION','Metodo')
	FICH.INT=LEERVALOR(DIR.DAT,'INTEGRALES','FicheroInt')
    IF (FICH.INT=="") FICH.INT=FICHD
	CALL DEFINE_FICH(FICH.INT,DIR.INT,FICH.INT,'INT')
     
    S1=RTC()	!LECTURA DEL TIEMPO EN SEGUNDOS
   
	MAT=0
    NUMINT=0

    IF(CLASMON=='LEE')CALL LEERINT(CLASMON,FICHD,MAT,NUMINT)
    SELECT CASE (CLASMON)
        CASE ('HAM','HAL','HAS','RND')
			CALL INTCMC(FICHD,MAT,NUMINT)
        CASE ('GSS')
			CALL INTGSS(FICHD,MAT,NUMINT)
	END SELECT

	S2=RTC()	!LECTURA DEL TIEMPO EN SEGUNDOS
	CALL TIEMPO(S2-S1,DIAS,HOR,MIN,SEG,TT)
	OPEN(1,FILE=DIR.INT,POSITION='APPEND',STATUS='UNKNOWN')
	WRITE(1,'(A)')'[TIEMPO]'
	WRITE(1,'(A,A)')'TiempoIntegracionDias=',TRIM(INTTOSTR(DIAS))
	WRITE(1,'(A,A)')'TiempoIntegracionHoras=',TRIM(INTTOSTR(HOR))
	WRITE(1,'(A,A)')'TiempoIntegracionMinutos=',TRIM(INTTOSTR(MIN))
	WRITE(1,'(A,A)')'TiempoIntegracionSegundos=',TRIM(REAL8TOSTR(SEG))
	WRITE(1,'(A,A)')'TiempoIntegracion=',TRIM(TT)
	CLOSE(1)

	UNASOLA=LEERVALOR_INT(DIR.DAT,'INTEGRALES','Integrales')
	IF (UNASOLA==0)THEN
		CALL METCALC(FICHD)

		S3=RTC()
		CALL TIEMPO(S3-S2,DIAS,HOR,MIN,SEG,TT)
		OPEN(1,FILE=DIR.MTD,POSITION='APPEND',STATUS='UNKNOWN')
		WRITE(1,'(A)')'[TIEMPO]'
		WRITE(1,'(A,A)')'TiempoDias=',TRIM(INTTOSTR(DIAS))
		WRITE(1,'(A,A)')'TiempoHoras=',TRIM(INTTOSTR(HOR))
		WRITE(1,'(A,A)')'TiempoMinutos=',TRIM(INTTOSTR(MIN))
		WRITE(1,'(A,A)'),'TiempoSegundos=',TRIM(REAL8TOSTR(SEG))
		WRITE(1,'(A,A)')'TiempoSCF=',TRIM(TT)
		CLOSE(1)

		MOMENTODIPOLAR=LEERVALOR_INT(DIR.DAT,'PROPIEDADES','MomentoDipolar')
		POBLACIONES=LEERVALOR_INT(DIR.DAT,'PROPIEDADES','Poblaciones')
		IF(MOMENTODIPOLAR==1.OR.POBLACIONES==1)	CALL PROPIEDADES(FICHD)
	ENDIF

	CALL ESCRIBIR(FICHD,NUMINT)
	
	STOP
END PROGRAM OMCM




