!---------------------------------------------------------------------
!  SUBROUTINE QUE CALCULA LA FUNCION DE PESO PARA LOS DESARROLLOS
!---------------------------------------------------------------------
	SUBROUTINE FPESO(NB1,NS1,NB2,NS2,P1,P2,P12)
	USE ESTRUCT
	USE GLOBAL
	
    TYPE (XYZ) :: P1,P2,P12	!COORDENADAS CARTESIANAS DEL CENTRO DE LAS 
							!FUNCIONES DE BASE Y DEL CENTRO

	REAL*16 RG1,RG2,DISTCENTROS
	CHARACTER*1 CI

    IF (UNASOLA=='S'.OR.UNASOLA=='s')THEN
		IF(CLASINT=='S'.OR.CLASINT=='s')THEN
			CI=CLASINT	
		ELSE
			CI=STIPO
		ENDIF
	ELSE
		CI=CLASINT
    ENDIF
	
    DENO= FB(NB1).SFB(NS1).PARAMETRO1+FB(NB2).SFB(NS2).PARAMETRO1
    IF(CI=='S')DENO= DENO + 3.0Q0
	IF(CI=='T')DENO= DENO + 2.5Q0
	IF(CI=='V')DENO= DENO + 2.0Q0
	IF(CI=='H')DENO= DENO + 2.5Q0
	IF(CI=='X')DENO= DENO + 4.0Q0
	IF(CI=='Y')DENO= DENO + 4.0Q0
	IF(CI=='Z')DENO= DENO + 4.0Q0
    IF(CI=='J')DENO= DENO + 3.0Q0
    IF (TIPOFB==1) THEN  
		!SELECCION DEL EXPONENTE DE LA FUNCION DE PESO (=EL QUE MENOR ERROR
		!SUMINISTRA PARA UNA INTEGRAL DE CALIBRADO).
		IF (P1.X==P2.X.AND.P1.Y==P2.Y.AND.P1.Z==P2.Z)THEN !MONOCENTRICA
			RG1=QSQRT(FB(NB1).SFB(NS1).PARAMETRO3)
			RG2=QSQRT(FB(NB2).SFB(NS2).PARAMETRO3)
			EXP0= (FB(NB1).SFB(NS1).PARAMETRO2+FB(NB2).SFB(NS2).PARAMETRO2+RG1+RG2)/DENO
		ELSE !BICENTRICA  LANDA=R/2*(ALFA1+ALFA2) MU=R/2*(ALFA1-ALFA2)
			RG1=QSQRT(FB(NB1).SFB(NS1).PARAMETRO3)
			RG2=QSQRT(FB(NB2).SFB(NS2).PARAMETRO3)
			DISTCENTROS=QSQRT((P1.X-P2.X)**2+(P1.Y-P2.Y)**2+(P1.Z-P2.Z)**2)
			EXP0=(FB(NB1).SFB(NS1).PARAMETRO2+FB(NB2).SFB(NS2).PARAMETRO2+RG1+RG2)*DISTCENTROS/2.Q0
			EXP1=(FB(NB1).SFB(NS1).PARAMETRO2-FB(NB2).SFB(NS2).PARAMETRO2+RG1-RG2)*DISTCENTROS/2.Q0
		ENDIF
	ELSEIF (TIPOFB==2) THEN  
        IF (P1.X==P2.X.AND.P1.Y==P2.Y.AND.P1.Z==P2.Z)THEN !MONOCENTRICA
			EXP0= (FB(NB1).SFB(NS1).PARAMETRO3/FB(NB1).SFB(NS1).PARAMETRO2+FB(NB2).SFB(NS2).PARAMETRO3/FB(NB2).SFB(NS2).PARAMETRO2)/(DENO*3.4Q0)
		ELSE !BICENTRICA  LANDA=R/2*(ALFA1+ALFA2) MU=R/2*(ALFA1-ALFA2)
			DISTCENTROS=QSQRT((P1.X-P2.X)**2+(P1.Y-P2.Y)**2+(P1.Z-P2.Z)**2)
			EXP0=(FB(NB1).SFB(NS1).PARAMETRO3/FB(NB1).SFB(NS1).PARAMETRO2+FB(NB2).SFB(NS2).PARAMETRO3/FB(NB2).SFB(NS2).PARAMETRO2)*DISTCENTROS/(2.Q0*3.4Q0)
            EXP1=(FB(NB1).SFB(NS1).PARAMETRO3/FB(NB1).SFB(NS1).PARAMETRO2-FB(NB2).SFB(NS2).PARAMETRO3/FB(NB2).SFB(NS2).PARAMETRO2)*DISTCENTROS/(2.Q0*3.4Q0)
		ENDIF
	END IF	
    END
