! ------------------------------------------------------------------
! --- SUBRUTINA QUE LEE LAS INTEGRALES DE UN ARCHIVO .INT
! ------------------------------------------------------------------
    SUBROUTINE PROPIEDADES(FICHERO)
    USE ESTRUCT
	USE GLOBAL
	
	CHARACTER*(*) FICHERO
	INTEGER*4 MAT,NUMINT
	CHARACTER*ILONG CADIDIOMA,LEERVALOR,CAD
	
	IDIOMA=LEERVALOR('idioma.lng','Idioma','Idioma')

	CALL DEFINE_FICH(FICH.DAT,DIR.DAT,TRIM(FICHERO),'DAT')
	CALL DEFINE_FICH(FICH.MTD,DIR.MTD,TRIM(FICHERO),'MTD')
	CALL DEFINE_FICH(FICH.PRP,DIR.PRP,TRIM(FICHERO),'PRP')
	CALL LEEDAT() !LECTURA DEL FICHEO DE DATOS
	CALL DEFINE_FICH(FICH.INT,DIR.INT,FICH.INT,'INT')
	CALL DEFINE_FICH(FICH.AUX,DIR.AUX,TRIM(FICHERO),'AUX')
	CALL LEETOQASINT()
	CALL DEFINE_FICH(FICH.SCR,DIR.SCR,TRIM(FICHERO),'SCR')
	
	CALL LEEMTD()

	CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1218')
	CAD=' '
	CALL MENSAJES(CADIDIOMA,CAD,105.5Q0)
	
	OPEN(1,FILE=DIR.PRP,STATUS='REPLACE')
	CLOSE(1)

	IF (MOMENTODIPOLAR==1)CALL MOMENTDIP()

	IF (POBLACIONES==1)CALL POBLACION()

	RETURN
    END

! ------------------------------------------------------------------
! --- SUBRUTINA QUE CALCULA EL MOMENTO DIPOLAR
! ------------------------------------------------------------------
	SUBROUTINE MOMENTDIP()
	USE GLOBAL
	USE ESTRUCT
	INTEGER*4 INPQ_F,I,IP,IQ
	!CHARACTER*ILONG CADIDIOMA,LEERVALOR,MENSAJE
	
	!CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1240')
	!WRITE(*,'(/,A)')TRIM(CADIDIOMA)
	!CALL GUARDAVALOR(DIR.DAT,'RESULTADOS','MENSAJE',TRIM(CADIDIOMA))
	
	PXEL=0.Q0
    PYEL=0.Q0
    PZEL=0.Q0
    DO I=1,N
		DO IP=1,N
			DO IQ=1,N
				INDICE=INPQ_F(IP,IQ)
				PXEL=PXEL-DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*XMAT(INDICE)
				PXEL=PXEL-DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*XMAT(INDICE)
				PYEL=PYEL-DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*YMAT(INDICE)
				PYEL=PYEL-DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*YMAT(INDICE)
				PZEL=PZEL-DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*ZMAT(INDICE)
				PZEL=PZEL-DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*ZMAT(INDICE)
			END DO
		END DO
	END DO

	PXNUC=0.Q0
    PYNUC=0.Q0
    PZNUC=0.Q0
    DO I=1,NUC
		PXNUC=PXNUC+NUCLEOS(I).CARGA*NUCLEOS(I).X
		PYNUC=PYNUC+NUCLEOS(I).CARGA*NUCLEOS(I).Y
		PZNUC=PZNUC+NUCLEOS(I).CARGA*NUCLEOS(I).Z
	END DO 
	PTX=PXNUC+PXEL
	PTY=PYNUC+PYEL
	PTZ=PZNUC+PZEL
	PMODUL=QSQRT(PTX*PTX+PTY*PTY+PTZ*PTZ)
	
	!CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1241')
	!WRITE(MENSAJE,'(A,A1,F10.5,A,F9.5,A)')TRIM(CADIDIOMA),':',PMODUL,' U.A. (=',PMODUL*2.541765Q0,' DEBYES)'
	!CALL GUARDAVALOR(DIR.DAT,'RESULTADOS','MENSAJE',TRIM(MENSAJE))

	CALL ESCPROP(0)
	
	RETURN
	END

! ------------------------------------------------------------------
! --- SUBRUTINA QUE CALCULA LAS POBLACIONES
! ------------------------------------------------------------------
	SUBROUTINE POBLACION()
	USE GLOBAL
	USE ESTRUCT
	INTEGER*4 I,IP,IQ,INPQ_F,ERROR
	REAL*16 RPJ2,RPJ
	!CHARACTER*ILONG CADIDIOMA,LEERVALOR,MENSAJE
	
	DEALLOCATE (POBEL,STAT=ERROR)	
	ALLOCATE (POBEL(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)POBEL(I)=0.Q0	
	DEALLOCATE (POSX,STAT=ERROR)	
	ALLOCATE (POSX(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)POSX(I)=0.Q0
	DEALLOCATE (POSY,STAT=ERROR)	
	ALLOCATE (POSY(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)POSY(I)=0.Q0
	DEALLOCATE (POSZ,STAT=ERROR)	
	ALLOCATE (POSZ(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)POSZ(I)=0.Q0
	DEALLOCATE (DPX,STAT=ERROR)	
	ALLOCATE (DPX(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)DPX(I)=0.Q0
	DEALLOCATE (DPY,STAT=ERROR)	
	ALLOCATE (DPY(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)DPY(I)=0.Q0
	DEALLOCATE (DPZ,STAT=ERROR)	
	ALLOCATE (DPZ(1:NUC),STAT=ERROR)
	IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	FORALL(I=1:NUC)DPZ(I)=0.Q0


    !CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1242')
	!WRITE(*,'(/,A)')TRIM(CADIDIOMA)
	!CALL GUARDAVALOR(DIR.DAT,'RESULTADOS','MENSAJE',TRIM(CADIDIOMA))
	!CADIDIOMA=LEERVALOR('idioma.lng',IDIOMA,'1243')
	!WRITE(MENSAJE,'(A,3X,A,5X,A,4X,A,5X,A,4X,A,5X,A,4X,A)')TRIM(CADIDIOMA),'P(A)','X(A)','(DX)','Y(A)','(DY)','Z(A)','(DZ)'
	!CALL GUARDAVALOR(DIR.DAT,'RESULTADOS','MENSAJE',TRIM(MENSAJE))
	!WRITE(MENSAJE,'(A,3X,A,5X,A,4X,A,5X,A,4X,A,5X,A,4X,A)')'-----','----','----','----','----','----','----','----'
	!CALL GUARDAVALOR(DIR.DAT,'RESULTADOS','MENSAJE',TRIM(MENSAJE))

	DO J=1,NUC
		DO I=1,N
			DO IP=1,N
				DO IQ=1,N
					INDICE=INPQ_F(IP,IQ)
					RPJ2=(FB(IP).X-NUCLEOS(J).X)**2+(FB(IP).Y-NUCLEOS(J).Y)**2+(FB(IP).Z-NUCLEOS(J).Z)**2
					RPJ=QSQRT(RPJ2)
					IF(RPJ<0.2Q0)THEN
						POBEL(J)=POBEL(J)+DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*S(INDICE)
						POBEL(J)=POBEL(J)+DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*S(INDICE)
						POSX(J)=POSX(J)+DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*XMAT(INDICE)
						POSX(J)=POSX(J)+DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*XMAT(INDICE)
						POSY(J)=POSY(J)+DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*YMAT(INDICE)
						POSY(J)=POSY(J)+DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*YMAT(INDICE)
						POSZ(J)=POSZ(J)+DBLE(NOCA(I))*CA(I,IP)*CA(I,IQ)*ZMAT(INDICE)
						POSZ(J)=POSZ(J)+DBLE(NOCB(I))*CB(I,IP)*CB(I,IQ)*ZMAT(INDICE)
					ENDIF
				END DO
			END DO
		END DO
	END DO 

	DO I=1,NUC
		IF (POBEL(I)/=0.Q0) THEN
			POSX(I)=POSX(I)/POBEL(I)
			POSY(I)=POSY(I)/POBEL(I)
			POSZ(I)=POSZ(I)/POBEL(I) 
			DPX(I)=POSX(I)-NUCLEOS(I).X
			DPY(I)=POSY(I)-NUCLEOS(I).Y
			DPZ(I)=POSZ(I)-NUCLEOS(I).Z
		ELSE
			POSX(I)=NUCLEOS(I).X
			POSY(I)=NUCLEOS(I).Y
			POSZ(I)=NUCLEOS(I).Z
			DPX(I)=0.Q0
			DPY(I)=0.Q0
			DPZ(I)=0.Q0
		ENDIF
		!WRITE(MENSAJE,'(I3,2X,F7.3,2X,3(F8.4,A2,F6.4,A1))')I,POBEL(I),POSX(I),' (',DPX(I),')',POSY(I),' (',DPY(I),')',POSZ(I),' (',DPZ(I),')'
		!CALL GUARDAVALOR(DIR.DAT,'RESULTADOS','MENSAJE',TRIM(MENSAJE))
	END DO
    CALL ESCPROP(1)

    RETURN
	END

! ---------------------------------------------------------------------------------
! --- SUBRUTINA PARA LEER LOS RESULTADOS DEL CALCULO SCF O MP2
! ---------------------------------------------------------------------------------
	SUBROUTINE LEEMTD()
	USE GLOBAL
	USE ESTRUCT
	CHARACTER*ILONG INTTOSTR
	INTEGER*4 LEERVALOR_INT
	REAL*16 LEERVALOR_REAL
	INTEGER*4 I,J,NELA,NELB,ERROR

	NELA=0
	DO I=1,N
		NOCA(I)=LEERVALOR_INT(DIR.MTD,'ESTADOELECTRONICO','NumOcupAlfa('//TRIM(INTTOSTR(I))//')')
		NELA=NELA+NOCA(I)
	ENDDO
	NELB=0
	DO I=1,N
		NOCB(I)=LEERVALOR_INT(DIR.MTD,'ESTADOELECTRONICO','NumOcupBeta('//TRIM(INTTOSTR(I))//')')
		NELB=NELB+NOCB(I)
	ENDDO
	
	!DEALLOCATE (CA,STAT=ERROR)
	!ALLOCATE (CA(1:N,1:N),STAT=ERROR)
	!IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	!DEALLOCATE (CB,STAT=ERROR)
	!ALLOCATE (CB(1:N,1:N),STAT=ERROR)
	!IF (ERROR/=0) STOP 'NO HAY MEMORIA SUFICIENTE'
	
	IF(NELA>0)THEN
		DO I=1,N
			DO J=1,N
				CA(I,J)=LEERVALOR_REAL(DIR.MTD,'ESTADOELECTRONICO','CoefOcupAlfa('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			ENDDO
		END DO
    ENDIF
	IF(NELB>0)THEN
		DO I=1,N
			DO J=1,N
				CB(I,J)=LEERVALOR_REAL(DIR.MTD,'ESTADOELECTRONICO','CoefOcupBeta('//TRIM(INTTOSTR(I))//','//TRIM(INTTOSTR(J))//')')
			ENDDO
		END DO
    ENDIF
	END

! ---------------------------------------------------------------------------------
! --- SUBRUTINA PARA GUARDAR LOS RESULTADOS DEL CALCULO DE PROPIEDADES MOLECULARES
! ---------------------------------------------------------------------------------
	SUBROUTINE ESCPROP(NIVEL)
	USE GLOBAL
	USE ESTRUCT
	CHARACTER*ILONG INTTOSTR
	CHARACTER*ILONG REALTOSTR
	INTEGER*4 NIVEL

	OPEN(1,FILE=DIR.PRP,POSITION='APPEND',STATUS='UNKNOWN')
	
	IF (NIVEL==0)THEN !GUARDA LOS DATOS DE LOS MOMENTOS DIPOLARES (ELECTRONICO, NUCLEAR Y TOTAL)
		WRITE(1,'(A)')'[MOMENTODIPOLAR]'
		WRITE(1,'(A,A)')'MomentoDipElecX=',TRIM(REALTOSTR(PXEL))
		WRITE(1,'(A,A)')'MomentoDipElecY=',TRIM(REALTOSTR(PYEL))
		WRITE(1,'(A,A)')'MomentoDipElecZ=',TRIM(REALTOSTR(PZEL))
		WRITE(1,'(A,A)')'MomentoDipNucX=',TRIM(REALTOSTR(PXNUC))
		WRITE(1,'(A,A)')'MomentoDipNucY=',TRIM(REALTOSTR(PYNUC))
		WRITE(1,'(A,A)')'MomentoDipNucZ=',TRIM(REALTOSTR(PZNUC))
		WRITE(1,'(A,A)')'MomentoDipTotX=',TRIM(REALTOSTR(PTX))
		WRITE(1,'(A,A)')'MomentoDipTotY=',TRIM(REALTOSTR(PTY))
		WRITE(1,'(A,A)')'MomentoDipTotZ=',TRIM(REALTOSTR(PTZ))
		WRITE(1,'(A,A)')'ModuloMomentoDip=',TRIM(REALTOSTR(PMODUL))
		WRITE(1,*)
	ENDIF

	IF (NIVEL==1)THEN !GUARDA LOS DATOS DE LAS POBLACIONES
		WRITE(1,'(A)')'[POBLACIONES]'
		DO I=1,NUC
			WRITE(1,'(A,A)')'Poblacion('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(POBEL(I)))
			WRITE(1,'(A,A)')'PosX('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(POSX(I)))
			WRITE(1,'(A,A)')'PosY('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(POSY(I)))
			WRITE(1,'(A,A)')'PosZ('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(POSZ(I)))
			WRITE(1,'(A,A)')'DespX('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(DPX(I)))
			WRITE(1,'(A,A)')'DespY('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(DPY(I)))
			WRITE(1,'(A,A)')'DespZ('//TRIM(INTTOSTR(I))//')=',TRIM(REALTOSTR(DPZ(I)))
		ENDDO
		WRITE(1,*)
	ENDIF

	CLOSE(1)
	END